### ISSUE TITLE
Is there a way to load Image from Bitmap or WriteableBitmet of SoftwareBitmap

### ISSUE THREAD

**Issue by pierresa** [takuya-takeuchi/FaceRecognitionDotNet#100]
Instead of creating Image from a file, is there any solution to load in memory Image (such are Bitmap, SoftwareBitmap or WriteableBitmap) into an Image usable  by face Recognition?

An example would be appreciated

Thank you
Pierre

**Comment by takuya-takeuchi** [comment]
@pierresa 
You can use this method.
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/blob/523039304ba29f2c2dde111c9ec94aae1e47edae/src/FaceRecognitionDotNet/FaceRecognition.cs#L506

This may be useful for you.
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/92

**Comment by pierresa** [comment]
Thank you

**Comment by pierresa** [comment]
Thank you
