### ISSUE TITLE
Illegal Instruction error on Xeon CPU

### ISSUE THREAD

**Issue by atabora1** [takuya-takeuchi/FaceRecognitionDotNet#101]
Hi @takuya-takeuchi 

I attempted to run a simple "FaceRecognitionDotNet" code on a computer with a Intel Xeon processor and received the following error message. Is it possible that FaceRecognitionDotNet isn't supported with this type of Intel x64 processor?

Error message.

The program '[2024] WpfApp2-core.exe' has exited with code -1073741795 (0xc000001d) 'Illegal Instruction'.

.NET Core 3.1
Windows 10
Code. 

 FaceRecognition _FaceRecognition1;
string tempModelDirectory = "models";
_FaceRecognition1 = FaceRecognition.Create(tempModelDirectory);//crashes on this line

I ran a program called "CPUZ" to see what the difference between CPU instructions were with a Xeon processor and my other computer with an i7 processor.

i7 computer
Instructions sets	"MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, EM64T, VT-x, AES,AVX, AVX2, FMA3"

Xeon computer
Instructions sets	"MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, EM64T, VT-x, AES"
Was missing, "AVX, AVX2, FMA3". 

Could this error be related to the CPU not being supported?

**Comment by takuya-takeuchi** [comment]
@atabora1 
FRDN depends on DlibDotNet. DlibDotNet does not support legacy cpu. CPU must support AVX instruction.
https://github.com/takuya-takeuchi/DlibDotNet/issues/172

You have to follow either of these.

* Use old FRDN (perhaps, 1.2.3.12 is last version to support legacy cpu)
* Build DlibDotNet without AVX flag and replace with it
  * Disable for https://github.com/takuya-takeuchi/DlibDotNet/blob/439e07e908ac9c1ccd7abe32d5f0ffbe4ba5bacf/nuget/BuildUtils.ps1#L424

**Comment by atabora1** [comment]
Thanks, I was able to use 1.2.3.12 successfully. 👍 I'll use this version for now and later attempt to build DLIB without the AVX instruction.

**Comment by takuya-takeuchi** [comment]
Close. The reporter looks like resolving issue.
