### ISSUE TITLE
Memory issue with Parallel Async tasks

### ISSUE THREAD

**Issue by atabora1** [takuya-takeuchi/FaceRecognitionDotNet#104]
Hi @takuya-takeuchi : I'm trying to utilize multi treads and parallel processing however it tends to consume almost all memory without freeing it. Your feedback would be greatly appreciated. 

[barebones.zip](https://github.com/takuya-takeuchi/FaceRecognitionDotNet/files/4642181/barebones.zip)

 public async void Button_Click_3(object sender, RoutedEventArgs e)
        {

            List<string> lstPhotos = new List<string>();
            List<Task> encodeTasks = new List<Task>();
            string tempModelDirectory = "models";
            FaceRecognitionGlobal = FaceRecognition.Create(tempModelDirectory);

            for(int x=0;x<80;x++)
            {
                lstPhotos.Add(@"models\obama-480p.jpg");

            }

            foreach(string strImg in lstPhotos)
            {
                  encodeTasks.Add(Task.Run(()=>TestImageASYNC(strImg)));

           
            }

        }//ends Button_Click_3

        public async Task TestImageASYNC(string imageToCheck)
        {

            //Tried using FaceRecognitionGlobal but I get "Access violation writing location"
            using (var FaceRecognitionFun = FaceRecognition.Create("models"))//Using this method consumes too much memory and eventually crashes
            {
                using (var unknownImage = FaceRecognition.LoadImageFile(imageToCheck))
                {
                    var faceLocations = FaceRecognitionFun.FaceLocations(unknownImage, 0, Model.Cnn).ToArray();
                    foreach (var faceLocation in faceLocations)
                    {
                        Debug.WriteLine($"{imageToCheck},{faceLocation.Top},{faceLocation.Right},{faceLocation.Bottom},{faceLocation.Left}");

                    }
                }

                // FaceRecognitionFun.Dispose();//This didn't help free up memory 
            }
            
        }//ends TestImageASYNC

**Comment by takuya-takeuchi** [comment]
@atabora1 

One point.
You should not create FaceRecognition object everytime.
This object is very heavy due to loading model files. And you should create it for each parallel thread.

However, I don't suppose working on multi thread.
Original python code looks like working fine but that is multi-process rather than multi thread.

It could help you.
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/24

**Comment by atabora1** [comment]
Thanks @takuya-takeuchi, much appreciated
