### ISSUE TITLE
Liveliness Detection

### ISSUE THREAD

**Issue by arnab77in** [takuya-takeuchi/FaceRecognitionDotNet#109]
Is there anyway we can check liveliness of the face

**Comment by takuya-takeuchi** [comment]
@arnab77in 
Nothing. I have no idea.
But I found https://www.pyimagesearch.com/2019/03/11/liveness-detection-with-opencv/

So we can implement net module by dlib and could use it in FRDN like https://github.com/takuya-takeuchi/FaceRecognitionDotNet/tree/master/src/DlibDotNet.Native.Dnn.GenderClassification

However, it is low priority and I know liveness detection is very hard to achieve high accuracy.
And I don't know there is dataset.
