### ISSUE TITLE
Random crashes in Unity

### ISSUE THREAD

**Issue by yashkaushal** [takuya-takeuchi/FaceRecognitionDotNet#11]
Hi @takuya-takeuchi, I've imported and used the library in an Unity project, however about half the times the library throws a runtime error: "This application has requested the runtime to terminate it in an unusual way. Please contact the application's support team for more information", in the cases when it doesn't crash, it works perfectly and gives output. I've tested this using faceEncodingPerformance code as well with same results.

I've used version 1.2.3.4 of FaceRecognitionDotNet and dependency on DlibDotNet version 19.15.0.20180916

**Comment by takuya-takeuchi** [comment]
Thanks for you interest in this project.

Do you know which method throw exception?
If we can specify problem method, I can concentrate to detect the bug.

Thank you for your cooperations.

**Comment by yashkaushal** [comment]
Thank you for support.
Using debugger to traverse single line at a time, It seem to get thrown from multiple methods which include FaceRecognition.Create(), FaceRecognition.LoadImageFile(), and faceRecognition.FaceEncodings().
After searching online I found this error message is thrown from C++'s abort() function, and looking at abort in Dlib's C++ source code in Davis King's repository, It seem to be a multi-threading related issue.

**Comment by takuya-takeuchi** [comment]
Honestly, I did not test code on multi-threading process.

Just in case, I have 1 question.
You call FaceRecognition.Create method again and again?
This method should be called on time.
I surprised FaceRecognition.Create throw exception.

**Comment by yashkaushal** [comment]
No, the FaceRecognition.Create method is called only once and its instance is used to compute encodings
Please see the below code block for reference
``` c#
        var loop = 10;
        using (var fr = FaceRecognition.Create(System.IO.Directory.GetCurrentDirectory() + "\\assets\\imageModels"))
        using (var image = FaceRecognition.LoadImageFile(System.IO.Directory.GetCurrentDirectory() + imagePath))
        {   
            var sw = new Stopwatch();
            sw.Start();
            
            for (var l = 0; l < loop; l++)
            {
                var encodings = fr.FaceEncodings(image);
                if (encodings == null)
                    continue;

                foreach (var encoding in encodings)
                    encoding.Dispose();
            }

            sw.Stop();

            var total = sw.ElapsedMilliseconds;
            var average = total / loop;            
        }
```

**Comment by takuya-takeuchi** [comment]
The above source code looks like to be FaceEncodingPerformance.
Did you faced the issue on the above code? I can not reproduce issue even increase loop count from 10 to 100 on Windows 10 1803.

I'm not familiar with Unity and I have no environmental Unity works but I installed Unity 2018.2.8f1 now.
So

1. Please give me sample project as long as simple and easy I can run.
1. Please tell me your environmental which issues occurred.

**Comment by yashkaushal** [comment]
Yes, it crashes about 20% of the time and while using the above code and about 50% time when trying to use those encoding to compare faces.

Please find the project at [this link](https://drive.google.com/file/d/1N9BOG-icYoaaI90L5CTkqsCN7uFETecQ/view?usp=sharing), It contains FaceRecognitionDotNet added and a script`TestFaceRecognition.cs` with two functions 
1. Which uses the above code to compute encoding repeatedly.
2. Which computes encoding once and compares it with webcam input.

You can comment out function call in `Start()` function(in the same script). It'll start executing by using play button on top.

My test system specs are 2x Xeon X5650, 24GB RAM, GTX 580(not using CUDA)

**Comment by takuya-takeuchi** [comment]
Hi yashkaushal.
Thank you for providing sample project.

I tried the following steps to reproduce issue. Is it correct?

1. Modify Assembly-CSharp.csproj to correct assembly path.
1. Comment out StartCoroutine(faceRecognition()) in Start
1. Enable encodingOnly in Start
1. Modify encodingOnly looks like
````
void encodingOnly()
    {
        var loop = 100;
        var directory = System.IO.Directory.GetCurrentDirectory() + "\\assets\\imageModels";
        // unknown property is "assets/images/obama.jpg" rather than assets\\images\\obama.jpg.
        // so cannot use it. why? Who does set it to unknown?
        var imagePath = Path.Combine(System.IO.Directory.GetCurrentDirectory(), this.unknown);
        using (var fr = FaceRecognition.Create(directory))
        using (var image = FaceRecognition.LoadImageFile(imagePath))
        {
            
            var sw = new Stopwatch();
            sw.Start();
            
            for (var l = 0; l < loop; l++)
            {
                var encodings = fr.FaceEncodings(image);
                if (encodings == null)
                    continue;

                foreach (var encoding in encodings)
                    encoding.Dispose();
            }

            sw.Stop();

            var total = sw.ElapsedMilliseconds;
            var average = total / loop;
            UnityEngine.Debug.Log($"Total: {total} [ms], Average: {average} [ms], Loop: {loop}");
        }
    }
````
5. Open FaceRecognitionTest directory by Unity
1. Rebuild
1. 'Attach To Unity & Play' in Visual Studio.
1. Then start program.
1. Done and Log will be shown

![image](https://user-images.githubusercontent.com/6241854/45913222-d3db2c80-be69-11e8-9578-3b5366cd0768.png)


"This application has requested the runtime to terminate it in an unusual way. Please contact the application's support team for more information" is not show. But Unity crashed sometime.
![image](https://user-images.githubusercontent.com/6241854/45913335-5d3f2e80-be6b-11e8-99ff-ea1889f54d3a.png)
![image](https://user-images.githubusercontent.com/6241854/45913270-5a900980-be6a-11e8-94f7-fbc79f2e67a7.png)

I'm not sure that what Unity crashes equals to issue you faced.
