### ISSUE TITLE
How do we get the raw encoding array so we can store in a DB?

### ISSUE THREAD

**Issue by jjohnson23112** [takuya-takeuchi/FaceRecognitionDotNet#111]
FaceEncoding doesn't seem to have methods to get the 128 doubles that define the face encoding.  Need that in order to store the faces in a database for fast querying.

**Comment by takuya-takeuchi** [comment]
@jjohnson23112 
Please check #54 or #106.
FRDN support serialization of endoing data or get raw double array data.
