### ISSUE TITLE
Detect other People in view

### ISSUE THREAD

**Issue by khinklenj** [takuya-takeuchi/FaceRecognitionDotNet#113]
Hi, 
I was using your code in the past to detect if more then one person was in the field of view for my web camera. It looks like recently that process has stopped working and the only code changes were I updated your library. Can you please let me know what changed or how I can best detect if more then one person in view.

Thank you
Keith

**Comment by takuya-takeuchi** [comment]
@khinklenj 
Please write down more details info.
What version did you use? And what version do you use?
And I think there is problem libs can not detect multiple person.

FRDN show lib can detect multiple person in this issue.
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/103

**Comment by khinklenj** [comment]
I am using the following version
DlibDotNet - 19.18.0.20200525
FaceRecognitionDotNet - 1.2.3.14

The purpose of my process is to take capture the webcam
1. Determine how many people are in the capture
2. Are any of the people in the capture known
   Known people have their images stored and I read them from a directory

Thanks

**Comment by takuya-takeuchi** [comment]
@khinklenj 
I checked both version by using example project.

Load mp4 file (source is https://www.youtube.com/watch?v=H8WuIajKzog) and detect whole frame.

````cs
var frameCount = 0;
using (var fr = FaceRecognition.Create("models"))
using (var videoCapture = new VideoCapture(filePath))
using (var rgb = new Mat())
    while (true)
    {
        using (var frame = videoCapture.RetrieveMat())
        {
            if (!frame.IsContinuous() || frame.Empty())
                break;

            frameCount++;
            Cv2.CvtColor(frame, rgb, ColorConversionCodes.BGR2RGB);

            var cols = rgb.Cols;
            var rows = rgb.Rows;
            var elems = rgb.ElemSize();

            // get the correct face landmarks
            var bytes = new byte[rows * cols * elems];
            Marshal.Copy(rgb.Data, bytes, 0, bytes.Length);
            // This line is for 1.3.0.1
            //using (var rgbSmallFrame = FaceRecognition.LoadImage(bytes, rows, cols, cols * elems, Mode.Rgb))
            // This line is for 1.2.3.14
            using (var rgbSmallFrame = FaceRecognition.LoadImage(bytes, rows, cols, 3))
            {
                var locations = fr.FaceLocations(rgbSmallFrame).ToArray();

                // get eyes
                foreach (var location in locations)
                {
                    var color = new Scalar(255, 0, 0);
                    var thickness = 4;

                    var l = location.Left;
                    var t = location.Top;
                    var b = location.Bottom;
                    var r = location.Right;
                    Cv2.Rectangle(frame, new OpenCvSharp.Point(l, t), new OpenCvSharp.Point(r, b), color, thickness);
                }
            }

            Cv2.ImShow("Video", frame);
            Cv2.WaitKey(1);

            if (save)
            {
                var path = Path.Combine(outputDirectory, $"{frameCount:D5}.jpg");
                Cv2.ImWrite(path, frame);
            }
        }
    }
````

Then Compare output image. But there is no different.

In conclusion, both versions have different interface but detection function does not degrade.

**Comment by takuya-takeuchi** [comment]
This picture comes from the above example.

![image](https://user-images.githubusercontent.com/6241854/85122986-69376a80-b262-11ea-920f-b20817efa43d.png)

**Comment by khinklenj** [comment]
How can I get the number of faces just

**Comment by takuya-takeuchi** [comment]
What? You mean You need to know number of faces in a frame, right?

`var num = locations.Length`
