### ISSUE TITLE
Dlib library doesn't seem to be using CUDA

### ISSUE THREAD

**Issue by jsdg-r** [takuya-takeuchi/FaceRecognitionDotNet#115]
Hi, I'm having issues with the cuda version of the library on linux. It doesnt seem to utilize the GPU at all. I have cuda 10.2 installed along with the corresponding FRDN library (1.3.0.1) but no matter what I seem to do it doesn't want to use cuda for gpu processing. I noticed something weird and have no idea if its related or not, but for version 1.2.3.14 of FRDN it seems to need dynamic dependencies for cuda while 1.3.0.1 doesn't.

1.3.0.1
ldd libDlibDotNetNativeDnn.so
        linux-vdso.so.1 (0x00007ffe259ea000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f14fb7e7000)
        libopenblas.so.0 => /usr/lib/x86_64-linux-gnu/libopenblas.so.0 (0x00007f14f9541000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f14f91b8000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f14f8e1a000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f14f8c02000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f14f8811000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f14fe08b000)
        libgfortran.so.4 => /usr/lib/x86_64-linux-gnu/libgfortran.so.4 (0x00007f14f8432000)
        libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f14f81f2000)

1.2.4.14
ldd linux-x64/native/libDlibDotNetNativeDnn.so
        linux-vdso.so.1 (0x00007fff5cd19000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8c61df3000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8c61bef000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f8c619e7000)
        libcublas.so.10.0 => not found
        libcudnn.so.7 => /usr/lib/x86_64-linux-gnu/libcudnn.so.7 (0x00007f8c460fd000)
        libcurand.so.10.0 => not found
        libcusolver.so.10.0 => not found
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8c45d74000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8c459d6000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8c457be000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8c453cd000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8c63915000)

I'm thinking this may be the issue but I'm not completely sure. Any help would be appreciated. Thank you!

**Comment by takuya-takeuchi** [comment]
@jsdg-r 
Thank you for your reporting.

It's terrible bug.
I replaced dependencies information from nuspec file.

````
        <dependency id="DlibDotNet" version="19.18.0.20200525" />
````

should be

````
        <dependency id="DlibDotNet.CUDA102" version="19.18.0.20200525" />
````

Thank you so very much!!!

**Comment by takuya-takeuchi** [comment]
Release 1.3.0.2!!
Could you try and check whether using CUDA?

**Comment by jsdg-r** [comment]
It is using cuda now :)
It seems to work with version 10.1 but 10.2 gives this error

error NU1102: Unable to find package DlibDotNet.CUDA102 with version (>= 19.18.0.20200525)
error NU1102:   - Found 1 version(s) in nuget.org [ Nearest version: 19.18.0.20200429 ]

The build failed. Fix the build errors and run again.
