### ISSUE TITLE
Performance FaceEncodings

### ISSUE THREAD

**Issue by lucascaser** [takuya-takeuchi/FaceRecognitionDotNet#116]
I used StopWatch to measure FaceEncondigs time and I realized that it is an average of 300ms. I read in other issues that I can use Intel MKL to improve performance. How to use this? Only import the dll's in the project with the option add new item? I downloaded the MKL and got the dll's but how to use it?

Ps .: Sorry my English, because I'm using the translator, I'm Brazilian

**Comment by takuya-takeuchi** [comment]
@lucascaser 
Next version, I distribute Intel MKL libs with nuget packge for windows.
But you may not wait it. Please check this wiki.
https://github.com/takuya-takeuchi/DlibDotNet/wiki/How-to-install#requirements

> Sorry my English, because I'm using the translator, I'm Brazilian
No problem. I'm Japanese. Do not hesitate to ask us about issue!!

**Comment by takuya-takeuchi** [comment]
sorry, next release does not contain MKL libs.
Because, current 1.3.0.1 nuget pacakge has bugs.
I want to resolve this issue at first.

Thanks a lot.

**Comment by lucascaser** [comment]
I managed to use MKL. I have another question. Can I ask here or do you prefer another issue?

**Comment by takuya-takeuchi** [comment]
@lucascaser 
Yes. Could you create new issue for everyone?

**Comment by unruledboy** [comment]
> I managed to use MKL. I have another question. Can I ask here or do you prefer another issue?

Hi, which version of MKL did you download? I tried 2020 it does not work. Where did you copy those dlls files to? Which folder exactly?

**Comment by takuya-takeuchi** [comment]
Windows and osx include mkl libs since 19.21.0.20210230
