### ISSUE TITLE
Looks like memory leak in FaceRecognitionModelV1.cs

### ISSUE THREAD

**Issue by ipernjakovic** [takuya-takeuchi/FaceRecognitionDotNet#117]
I've only noticed this when i used a large image for FaceEncodings.

To recreate, try this, and i've attached an image that i used, but it can really be any large image.

[IMG_20170626_142736.zip](https://github.com/takuya-takeuchi/FaceRecognitionDotNet/files/4836149/IMG_20170626_142736.zip)

```
Using fr = FaceRecognition.Create(".")
            Using img = FaceRecognition.LoadImageFile("IMG_20170626_142736.jpg")

                Dim faces = fr.FaceLocations(img, 0, Model.Hog)
                Dim encodings = fr.FaceEncodings(img, faces)
                For x = 0 To encodings.Count - 1
                    encodings(x).Dispose()
                Next

            End Using
End Using

```

This will take around 1Gb of memory, and it will not release it. 

I can also tell you exactly where the memory jump happens, its in "FaceRecognitionModelV1.cs", this line:
 ```
         // extract descriptors and convert from float vectors to double vectors
                var descriptors = net.Operator(faceChips, 16);
```

but i dont know why its not released back.

Thanks
Ivan.

EDIT: I've tested with smaller image and memory consumption is similar even with 640x480 image. Around 800mb for FaceEncodings. Not sure thats normal. I will test more.

**Comment by takuya-takeuchi** [comment]
@ipernjakovic 
I'm very sorry to late reply.

> I can also tell you exactly where the memory jump happens

Maybe, this timing is first time to forward dnn.

> but i dont know why its not released back.

I expect that all memory will be released when FaceRecognition object is just disposed.
But it does not work accroding to what you saw.
It is weird.
