### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL 'DlibDotNetNativeDnn' or one of its dependencies: The specified module could not be found. (0x8007007E)

### ISSUE THREAD

**Issue by prafull-chaure** [takuya-takeuchi/FaceRecognitionDotNet#122]
I am trying to run my application on two different systems with same configuration(Intel i5 4th generation Windows 10 Pro), but it works perfectly on one system and another system showing below error. Please guide me to resolve.

Error in Main Method - System.TypeInitializationException: The type initializer for 'DlibDotNet.NativeMethods' threw an exception.
---> System.DllNotFoundException: Unable to load DLL 'DlibDotNetNativeDnn' or one of its dependencies: The specified module could not be found. (0x8007007E)
at DlibDotNet.NativeMethods.LossMetric_anet_type_create()
at DlibDotNet.NativeMethods..cctor()
--- End of inner exception stack trace ---
at DlibDotNet.NativeMethods.get_frontal_face_detector()
at DlibDotNet.Dlib.GetFrontalFaceDetector()
at FaceRecognitionDotNet.FaceRecognition..ctor(String directory)

**Comment by takuya-takeuchi** [comment]
@prafull-chaure 
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/wiki/Quickstart

# Checkpoint

* Install Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019
* If use FRDN.CUDXXX, install cudnn
* If use FRDN.MKL, deploy mkl libs
* Check dependencies by using https://github.com/lucasg/Dependencies.
  * You can find the missing libraries which be depended on DlibDotNetNativeDnn.

And what did you use framework? .NET framewrok? .NET core?
If .NET framework, libraries are not copied to application directory.

**Comment by prafull-chaure** [comment]
@takuya-takeuchi 
Thank you for your response.
I'm using .Net core 3.1 and also installed Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019, but still showing same error.

**Comment by takuya-takeuchi** [comment]
@prafull-chaure 
Ok. So check the **%USERPROFILE%\.nuget\packages\dlibdotnet\19.20.0.20200725\runtimes\win-x64\native**/
I don't know what exact version of FRDN. So 19.20.0.20200725 is missing. But you could choice lastest.
Then, execute https://github.com/lucasg/Dependencies and open DlibDotNetNativeDnn.
You can find the missing libraries.

**Comment by MarioGK** [comment]
Hi i am having the exact same issue, and the Dependencies app is not showing anything missing

![image](https://user-images.githubusercontent.com/8379079/157714222-467b07f3-8403-4d69-90cf-b6aa0df2ace5.png)

![image](https://user-images.githubusercontent.com/8379079/157714147-84dc7fd5-79a1-47a5-ac2e-2414e986b5e9.png)
