### ISSUE TITLE
What am I missing for CUDA usage?

### ISSUE THREAD

**Issue by Anachostic** [takuya-takeuchi/FaceRecognitionDotNet#123]
I've been struggling trying to get a CUDA-enabled process working on my system.  There is a real lack of any definitive process for system setup and verification.

To get to the point I am at, I downloaded NuGet packages for FaceRecognitionDotNet.CUDA101, which included DlibDotNet.CUDA101.  Wrote the code and compiled.  As was my experience with the non-CUDA version, I had to manually copy the "Native" dlls from the package into the bin folder.

I installed NVIDIA GPU Computing toolkit (v 10.1) and got the DNN files for 10.1.  Plenty of errors trying to run my app and I used SysInternals ProcMon to find out what files were being looked for and were missing.  I had to copy cublas64_10 and cublasLt64_10 DLLs into my bin folder as it wouldn't look in the NVIDIA folders.  I then found that the cudnn64 DLL was the wrong version.  I had cudnn64_8 when i needed cudnn64_7, which required hunting in NVIDIA's archives for the right download.  Again, this had to be put in the bin folder.

Now, the app runs without throwing any errors, but has no speed difference than using CPU and the task manager does not indicate any GPU usage.  I've gotten this far with trial and error, but now feel I've run out of ideas.  What am I missing?

**Comment by takuya-takeuchi** [comment]
@Anachostic 
Sorry, late response.

> CPU and the task manager does not indicate any GPU usage

Which functions do you talk about?
FaceDetection does not use GPU in hog mode. It is limitation of dlib other than FRDN.
Please use cnn mode for FaceLocations.

**Comment by Anachostic** [comment]
Thank you for the reply.  No worries about the response time.  This is only a hobby for me.

You are correct in guessing it is FaceLocations that is where the bottleneck is.  You introduced some new terms (hog/cnn) that I had to research.  After some reading, I looked at the API and see the overload for FaceLocations has a parameter for that.

faceLocations = Common.FaceRecogition.FaceLocations(img, model:=Model.Cnn)

Unfortunately, after a rebuild and another test run, the performance has not changed and there is no measure of activity on my GPU in Task Manager.  In fact, the CPU usage grew substantially.  I guess that's to be expected based on what I read about CNN mode.

**Comment by takuya-takeuchi** [comment]
@Anachostic 

You can measure performance by https://github.com/takuya-takeuchi/FaceRecognitionDotNet/tree/master/examples/Benchmark

````
dotnet add package FaceRecognitionDotNet.CUDA102
dotnet run -c Release -m Models
Benchmarks

Timings at 240p:
 - Face locations: 0.0466s (21.46 fps)
 - Face landmarks: 0.0012s (833.33 fps)
 - Encode face (inc. landmarks): 0.0036s (277.78 fps)
 - End-to-end: 0.0508s (19.69 fps)

Timings at 480p:
 - Face locations: 0.1834s (5.45 fps)
 - Face landmarks: 0.0012s (833.33 fps)
 - Encode face (inc. landmarks): 0.0036s (277.78 fps)
 - End-to-end: 0.1880s (5.32 fps)

Timings at 720p:
 - Face locations: 0.4132s (2.42 fps)
 - Face landmarks: 0.0012s (833.33 fps)
 - Encode face (inc. landmarks): 0.0034s (294.12 fps)
 - End-to-end: 0.4180s (2.39 fps)

Timings at 1080p:
 - Face locations: 0.9282s (1.08 fps)
 - Face landmarks: 0.0012s (833.33 fps)
 - Encode face (inc. landmarks): 0.0036s (277.78 fps)
 - End-to-end: 0.9354s (1.07 fps)
````

After the above, modify Program.cs

````diff
-            var faceLocations = FaceRecognition.FaceLocations(image).ToArray();
+            var faceLocations = FaceRecognition.FaceLocations(image, 1, Model.Cnn).ToArray();
````

And run, 


````
Benchmarks

Timings at 240p:
 - Face locations: 0.0194s (51.55 fps)
 - Face landmarks: 0.0012s (833.33 fps)
 - Encode face (inc. landmarks): 0.0034s (294.12 fps)
 - End-to-end: 0.0508s (19.69 fps)

Timings at 480p:
 - Face locations: 0.0756s (13.23 fps)
 - Face landmarks: 0.0012s (833.33 fps)
 - Encode face (inc. landmarks): 0.0034s (294.12 fps)
 - End-to-end: 0.1880s (5.32 fps)

Timings at 720p:
 - Face locations: 0.1658s (6.03 fps)
 - Face landmarks: 0.0014s (714.29 fps)
 - Encode face (inc. landmarks): 0.0034s (294.12 fps)
 - End-to-end: 0.4184s (2.39 fps)

Timings at 1080p:
 - Face locations: 0.3750s (2.67 fps)
 - Face landmarks: 0.0014s (714.29 fps)
 - Encode face (inc. landmarks): 0.0036s (277.78 fps)
 - End-to-end: 0.9364s (1.07 fps)
````

GPU works well.
My machine has GTX 1080 and i7-8700.

**Comment by takuya-takeuchi** [comment]
End-to-end has something wrong. But Face locations improves.

**Comment by Anachostic** [comment]
Thank you.  The Benchmark demo was exactly what I was looking for.  For reference, here are my numbers.  My development machine is an AMD Ryzen 5 1600 with a simple GEForce 9500 GT card.  I don't attempt CUDA on that.  I have a deployment machine that is tasked with running recognition on about 3 million photos and it is an older AMD FX 8120 with a GeForce GTX 660 Ti, which I was hoping to use the CUDA processing on.

Dev Computer CPU
Benchmarks

Timings at 1080p:
- Face locations: 1.0972s (0.91 fps)
- Face landmarks: 0.0032s (312.50 fps)
- Encode face (inc. landmarks): 0.3410s (2.93 fps)
- End-to-end: 1.4440s (0.69 fps)

Deployment Machine CPU
Benchmarks

Timings at 1080p:
- Face locations: 2.0418s (0.49 fps)
- Face landmarks: 0.0032s (312.50 fps)
- Encode face (inc. landmarks): 0.9324s (1.07 fps)
- End-to-end: 2.9736s (0.34 fps)

Deployment machine GPU
Benchmarks

Timings at 1080p:
- Face locations: 1.1862s (0.84 fps)
- Face landmarks: 0.0030s (333.33 fps)
- Encode face (inc. landmarks): 0.0110s (90.91 fps)
- End-to-end: 2.1048s (0.48 fps)

The end result is that the performance difference is not significant enough on my hardware between CPU and GPU.  When using CNN mode, there is more CPU used even when using the GPU, which limits the number of instances I can run at one time.  It is actually better for me to have an extra instance or two running using CPU.

I appreciate your support in leading me to this decision.  Thank you for this library.

**Comment by takuya-takeuchi** [comment]
@Anachostic 
TBH, face location of dlib is a bit slow.
We can use other library to find face and dlib should be used for only face matching.
But I'm not sure there is high performance face find library support C++.

ncnn looks like to support face finding.
https://github.com/Tencent/ncnn#%E6%94%AF%E6%8C%81%E5%A4%A7%E9%83%A8%E5%88%86%E5%B8%B8%E7%94%A8%E7%9A%84-cnn-%E7%BD%91%E7%BB%9C
But I don't know exact number of performance.
