### ISSUE TITLE
Provide examples for Landmark detection

### ISSUE THREAD

**Issue by sr229** [takuya-takeuchi/FaceRecognitionDotNet#124]
Despite having an API, I clearly have no clue how to perform landmark recognition since there is a lack of a concrete example and documentation regarding using the face landmark class.

**Comment by takuya-takeuchi** [comment]
@sr229 
You can use this example.
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/blob/e91da42cabb351bc841b2ceead5270fe11225a8a/examples/BlinkDetection/Program.cs#L65

This example focuses on detection eye blink.
`faceLandmark` has 68 or 5 landmark.

**Comment by sr229** [comment]
Looks like that works, thanks!
