### ISSUE TITLE
Error The type initializer for 'DlibDotNet.NativeMethods' threw an exception

### ISSUE THREAD

**Issue by khinklenj** [takuya-takeuchi/FaceRecognitionDotNet#125]
Hi
I am getting the following error message.
The type initializer for 'DlibDotNet.NativeMethods' threw an exception. stack:    at DlibDotNet.NativeMethods.get_frontal_face_detector()
   at FaceRecognitionDotNet.FaceRecognition..ctor(String directory)
   at FaceRecognitionDotNet.FaceRecognition.Create(String directory)

I am running a windows 10 machine with an onboard graphics 
its Intel hd graphic 2000
The cpu is an intel i7

Please let me know how i can correct this

Thanks
Keith

**Comment by takuya-takeuchi** [comment]
@khinklenj 
As long as I remember, you should be successful to run FRDN.

https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/113
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/105
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/78

Please write down what you changed, e.g. OS, package version etc.

And you can detail error code in Event Viewer. It could be helpful.

**Comment by khinklenj** [comment]
The issue was because of a on board gpu using an outdated driver
