### ISSUE TITLE
Detect person looking at camera in background

### ISSUE THREAD

**Issue by khinklenj** [takuya-takeuchi/FaceRecognitionDotNet#126]
How can i better detect if a person is in the background look over my shoulder

Like in this image I want to be able to detect the man looking over the woman's shoulder

![man-peering-over-womans-shoulder-BBAJFJ](https://user-images.githubusercontent.com/6447184/90300864-8b1c2a80-de6a-11ea-84cc-2e22a065b0a3.jpg)

**Comment by takuya-takeuchi** [comment]
@khinklenj 

As long as I bethink of, you must implement eye gaze estimation.
But FRDN does not support.
And it requires high resolution picture to detect human eye.

**Comment by khinklenj** [comment]
Thank you
