### ISSUE TITLE
Unhandled stride is less than column.

### ISSUE THREAD

**Issue by khinklenj** [takuya-takeuchi/FaceRecognitionDotNet#129]
I am getting the following error since i updated

capture.Read(frame);

                    int NumPeople = 0;

                    var array = new byte[frame.Width * frame.Height * frame.ElemSize()];
                    Marshal.Copy(frame.Data, array, 0, array.Length);

                    WebCapture = FaceRecognition.LoadImage(array, frame.Rows, frame.Cols, frame.ElemSize(), Mode.Rgb);
                    using (var rgbSmallFrame = FaceRecognition.LoadImage(array, frame.Rows, frame.Cols, frame.ElemSize(), Mode.Rgb))
                    {
                        var locations = fr.FaceLocations(rgbSmallFrame).ToArray();
                        NumPeople = locations.Length;
                    }

Winform - Unhandled stride is less than column.
Parameter name: stride
   at FaceRecognitionDotNet.FaceRecognition.LoadImage(Byte[] array, Int32 row, Int32 column, Int32 stride, Mode mode)

**Comment by takuya-takeuchi** [comment]
@khinklenj 
`frame.ElemSize()` is not correct. 4th argument is stride rather than element size.
Basically, this arugment is `element size * columns`.

P.S.
Please close issue if you will be successful to resolve issue.
