### ISSUE TITLE
.Net Core Support Camera Real Time Face Recognition

### ISSUE THREAD

**Issue by dev0karim0yassine** [takuya-takeuchi/FaceRecognitionDotNet#13]
Hi takuya;
Thank you for sharing this
i just want to know if i can use this to create a **real time** **face recognition** and also if it support the **Asp** (**MVC 5 / Core**)
Thanks

**Comment by takuya-takeuchi** [comment]
Thank you for interesting this project.

Honestly, I didn't try it on MVC/Core.
I confirmed that this library works on only WinForms, WPF, UWP and .Net core console.

**Comment by eloelo22** [comment]
I have made a web application using .net core the razor pages as far as i remember i am submitting the photo through a webApi then return the results for possible matches but i will confirm il post the update later

**Comment by dev0karim0yassine** [comment]
Hi Takuya,
Thank you for your respond, i will give a shot in a web app project and see if it works
Tnaks

**Comment by GaikwadPratik** [comment]
@takuya-takeuchi  , can I use this library along with camera? if so, do you have any example that I can follow?

**Comment by takuya-takeuchi** [comment]
Yes. But this library does not provide camera function.
You can get image from webcam by using OpenCVSharp, Aforge.NET or UWP MediaCapture.
