### ISSUE TITLE
 System.DllNotFoundException: Unable to load DLL 'DlibDotNetNative': A dynamic link library (DLL) initialization routine failed. (Exception from HRESULT: 0x8007045A)

### ISSUE THREAD

**Issue by vikrant-bioenable** [takuya-takeuchi/FaceRecognitionDotNet#131]
2020-08-26 18:11:43.163	Error	Error in Main Method - System.DllNotFoundException: Unable to load DLL 'DlibDotNetNative': A dynamic link library (DLL) initialization routine failed. (Exception from HRESULT: 0x8007045A)
   at DlibDotNet.NativeMethods.get_frontal_face_detector()
   at FaceRecognitionDotNet.FaceRecognition..ctor(String directory)
   at FaceRecognitionDotNet.FaceRecognition.Create(String directory)
   at Camera_Capture_ConsoleApplication.Program.Main(String[] args) in C:\Users\.....\Documents\Visual Studio 2005\Projects\Camera_Capture_ConsoleApplication\Camera_Capture_ConsoleApplication\Program.cs:line 3139
2020-08-26 18:11:43.166	Error	Error in Main Method - Unable to load DLL 'DlibDotNetNative': A dynamic link library (DLL) initialization routine failed. (Exception from HRESULT: 0x8007045A)

at line :
  fr = FaceRecognition.Create("C:\\WFH_Client\\models");

working on some machines and not on some machine

machine config : windows 10 pro 64 bit

**Comment by takuya-takeuchi** [comment]
@vikrant-bioenable 
Could you check this issue?
https://github.com/takuya-takeuchi/DlibDotNet/issues/153

**Comment by vikrant-bioenable** [comment]
my cpu is intel i5 7th generation...... it works on some machine perfectly...but on some machine showing above error... i had installed VC_redist.x64.exe also. file version - 14.26.28720.3

**Comment by takuya-takeuchi** [comment]
@vikrant-bioenable 

````
C:\Users.....\Documents\Visual Studio 2005
````

Are you kidding? Do you use VS 2005?
I doubt your machine does not have VC++ 2017 runtime.

**Comment by vikrant-bioenable** [comment]
I have installed VC++ 2015-2019 runtime... please see attached image
![Capture](https://user-images.githubusercontent.com/69619591/91439199-345f1980-e88a-11ea-88bd-c888be24fa1c.PNG)

**Comment by vikrant-bioenable** [comment]
I am using Visual Studio 2019....just project saved location was vs 2005....... as of your dll not even open in visual studio 2015.....

**Comment by takuya-takeuchi** [comment]
@vikrant-bioenable 
I have a few time to check issue.
Could you give the minimum sample project reproduce issue?

**Comment by vikrant-bioenable** [comment]
Hello sir , please find my source code build in Visual Studio 2019 - having above mentioned issue at below line - 

 fr = FaceRecognition.Create(AppRootPath + "\\models"); 
 
GITHUB LINK - 
https://github.com/vikrant-bioenable/DemoProjectFacerecognition.git

**Comment by vikrant-bioenable** [comment]
Dear Sir.., Please update.. I am stucked here...

**Comment by takuya-takeuchi** [comment]
sorry, I lost your message.
let me check again.
thanks

**Comment by takuya-takeuchi** [comment]
![image](https://user-images.githubusercontent.com/6241854/94340431-ac149580-003c-11eb-95b0-2df31acef316.png)

1. Open solution file by VS2019
2. Debug by F5
3. Stop on the above break point

And created Hyper-V machine, install only VS2019.
After this, did the avobe steps again.
But there is no issue.

![image](https://user-images.githubusercontent.com/6241854/94340799-77560d80-003f-11eb-8d8b-9b93425806a2.png)


I can not reproduce your issue.

**Comment by vikrant-bioenable** [comment]
Dear Sir, On my machine also it works very fine.... but on client machine this code fails at fr = FaceRecognition.Create(AppRootPath + "\models");

**Comment by popy2k14** [comment]
Just for reference, has the same issue and was solved by using an older build for cpus without AVX instruction set.
See here: https://github.com/takuya-takeuchi/DlibDotNet/issues/153#issuecomment-553400395

**Comment by lequangtuananh93** [comment]
Maybe the reason is need to install old Net Framework version like 2.0, 3.0, 3.5,....it's worked for me :D
