### ISSUE TITLE
Models not found in repository

### ISSUE THREAD

**Issue by eyanson** [takuya-takeuchi/FaceRecognitionDotNet#136]
Hello. When execute this: _FaceRecognition = FaceRecognition.Create(directory)

I take this error: System.IO.FileNotFoundException: 'C:\Users\xxx\source\repos\TestFaceRecognition\TestFaceRecognition\bin\x64\Debug\Models\shape_predictor_68_face_landmarks.dat'

In "Models" folder on your repository there is not model files. Where I found those files?
Thanks.

**Comment by cinek1** [comment]
You can download this file from here https://github.com/AKSHAYUBHAT/TensorFace/tree/master/openface/models/dlib

**Comment by subha219** [comment]
HOW TO TEST IT ?
