### ISSUE TITLE
Possible to use CUDA in Head Pose Training?

### ISSUE THREAD

**Issue by LovelyA72** [takuya-takeuchi/FaceRecognitionDotNet#137]
I am trying to use 300LP dataset to run this tool. However, the training speed decreases drastically as the training goes. It also starts to use a scary amount of RAM. 

Is it possible to increase the speed of Head Pose Training with CUDA? I am currently using DlibDotNet.CUDA101 with proper CUDA driver installed. But the GPU usage was still 0 during the training process.

What should I do to use CUDA in my Head Pose Training?

Thank you!

**Comment by takuya-takeuchi** [comment]
@LovelyA72 
Head Pose Training does not use GPU.
It uses Krls kernel.
This issue is not FRDN.

Thanks.

**Comment by LovelyA72** [comment]
OK~ Thank you for your reply.
