### ISSUE TITLE
Follow up question regarding HeadPoseTraining

### ISSUE THREAD

**Issue by LovelyA72** [takuya-takeuchi/FaceRecognitionDotNet#138]
Thank you for your clarification on my GPU question a few days ago!
I now have another issue. As the training progresses, the time that took to process each image increases significantly.
When the training reaches 40%, it's already taking more than 8 sec for one image(I am using 300W-LP), which means that the training will take forever to complete. 

I am currently using:
AMD Ryzen 3700
32GB DDR4 RAM running at around 2100Mhz

This setup is giving me poor training performance. Are there any solution or tips for increasing the training speed?
Or can the training software being further optimised to increase performance(e.g. split training into separate sections and clear the RAM after each section completes)?

Thank you!

**Comment by takuya-takeuchi** [comment]
@LovelyA72 

> When the training reaches 40%, it's already taking more than 8 sec for one image(I am using 300W-LP)

I guess row angle training is very slow.
You mean all angle trainings are slow, right?
And one image is not one epoch?

I does not have machine with Ryzen.
Prebuild binaries are built on intel cpu and it may cause low machine on not intel machine.

> split training into separate sections

I have never try it.
But you may be able to do the following.

1. training small data and create model data
2. load created model data and reinforce it by new training data

But current training script does not support load trained model.

**Comment by LovelyA72** [comment]
Thank you for your information. While I am writing the actual training is almost complete. It just needs a large and fast RAM and a beefy CPU.
