### ISSUE TITLE
Increase accuracy

### ISSUE THREAD

**Issue by nShieldSolo** [takuya-takeuchi/FaceRecognitionDotNet#140]
Hi @takuya-takeuchi,
  
  Thanks for your great library. I used your library to get the face encoding and save it as text file. I have created a dictionary with 1 key and many values ​​(face encoding) for a people. Then, I took the identification to check in the dictionary list to know who it is. 
    Can you tell me that I can use this? What do I have to do to increase accuracy?

Please take care your health. 
Many thanks

**Comment by takuya-takeuchi** [comment]
@nShieldSolo 
> I took the identification to check in the dictionary list to know who it is.

I think you can do what you think.

````csharp
var persons = new Dictionary<string, List<FaceEncoding>>();
````

In this case, 1 person has multiple face encoding data.
It means that all values should take small distance from truth data.
Then, you can check average of distances and compare with others.
Correct data should be minimum value.
