### ISSUE TITLE
FaceRecognition.Create working on memory (taking byte[] as parameter)

### ISSUE THREAD

**Issue by ADD-eNavarro** [takuya-takeuchi/FaceRecognitionDotNet#147]
Hello Takeuchi-san.

I have created a face recognition system using your wonderful work, thank you very much. 
Only, my enterprise works with microservices, and in order to implement the f.r. system into one I would need to work independently of the file system. There, I stumble upon _FaceRecognition.Create_, which only takes a folder path as input.
I've been looking into it and basically what _Create_ does is deserialize all 4 model files using DlibDotNet. Deserialize method in _DlibDotNet.Dnn.LossMmod.cs_ and _.Dnn.LossMetric.cs_ both take a file, check if it exists and turn it into a byte array, then they do the proper deserializing.
I was wondering, could it be possible to create an overload for these _Deserialize_ methods that takes directly a byte array, and extend that up to the _Create_ method, so that **FaceRecognition.Create(byte[] resnetModel, byte[] faceDetector, byte[] 5faceLandmarks, byte[] 68faceLandmarks)** could be used as an overload (along with the already existing method print)?
I really love your work and would like to keep using it as you publish it, without internal tinkering.

Thank you again.

**Comment by takuya-takeuchi** [comment]
@ADD-eNavarro 
 Can not agree with your suggestion.
But I can add the following interface

````
var model = new Model {  ResNet = File.ReadAllBytes("test.dat"), ... } ;
var fr = FaceRecognititionDotNet.Create(model);
````

Because

* I do NOT want to add new argument if FRDN support new model file

However

* DlibDotNet does not support deserialize from byte array

So we have to update DlibDotNet at first.

Thanks.

**Comment by ADD-eNavarro** [comment]
Hi again!

Your solution seems right to me. 
Are you going to open PR in DlibDotNet to implement deserialization from byte array?

**Comment by takuya-takeuchi** [comment]
@ADD-eNavarro 
Yes. Just start to implement deserialize.
https://github.com/takuya-takeuchi/DlibDotNet/tree/deserialize

But I should take a long time for long long build time.
Because DlibDotNet.Native and DlibDotNet.Native.Dnn uses numerous template class.
Please be patient.

**Comment by ADD-eNavarro** [comment]
Hello again.

I will be patient, I know good work takes time. 
But my boss wants me to sketch a roadmap for the deployment, so I was wondering: would it be possible to have some idea of how long are we talking about? Weeks, months? Any information will be very useful.

**Comment by takuya-takeuchi** [comment]
@ADD-eNavarro 
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/commit/9a3f39aa4df48576e5366ea105889caf5bb2552d

It could work on win and Linux.
osx can not pass test due to dependencies.
So I can't publidh nuget package now.

**Comment by takuya-takeuchi** [comment]
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/wiki/Quickstart#1-initialize

**Comment by ADD-eNavarro** [comment]
Hello again.

With a colleague we're trying to create the NuGet package from the development branch, but we get an error, missing DlibDotNet native dlls. So we were wondering if you could help on this matter, maybe even create the NuGet package yourself from this branch (and yes, we are aware it wouldn't work on osx).

**Comment by takuya-takeuchi** [comment]
@ADD-eNavarro 

>but we get an error, missing DlibDotNet native dlls. 

You can pick them from nuget file.
https://www.nuget.org/packages/DlibDotNet/

**Comment by takuya-takeuchi** [comment]
@ADD-eNavarro 
Release 1.3.0.3
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/releases/tag/1.3.0.3
