### ISSUE TITLE
How to enable MKL support for FaceEncoding?

### ISSUE THREAD

**Issue by neonleo** [takuya-takeuchi/FaceRecognitionDotNet#171]
I have using FaceRecognitiinDotNet.MKL package from Nuget and install intel MKL, following the document, I copy the Dll to the bin folder, but is it any bool.type of flag like .UseMKL = true, I have to turn it on?

**Comment by takuya-takeuchi** [comment]
@neonleo 
You have nothing to do.
FaceRecognitiinDotNet.MKL depends on DlibDotNet.MKL and DlibDotNet is only built with Intel MKL.
So we have no method to make disable/enable using MKL.

Thanks.

**Comment by neonleo** [comment]
Thank you!

**Comment by programatix** [comment]
Do I need to install Intel oneAPI Math Kernel Library for DlibDotNet.MKL to use MKL?

**Comment by takuya-takeuchi** [comment]
You must install DlibDotNet.MKL and deploy MKL binaries to application directory.
Please check https://github.com/takuya-takeuchi/DlibDotNet/wiki/How-to-install#requirements

**Comment by programatix** [comment]
Hi,

Thanks for the reply. I have already included the DlibDotNet.MKL and I have files stated in the requirement,
![image](https://github.com/takuya-takeuchi/FaceRecognitionDotNet/assets/3293865/9f43897f-6ce2-4d82-a7a8-b3107cf1b827)

This mean that everything has already set up correctly, and I do not need to install Intel Math Kernel Library or include intelmkl.redist.win-x64 package, right?

I'm a bit confused as I do not see any performance gain when using MKL vs non-MKL packages. I thought I have set up wrongly and the FaceRecognitionDotNet.MKL/DLibDotNet.MKL just fallback to non-MKL when insufficient library/runtime found.

**Comment by takuya-takeuchi** [comment]
> This mean that everything has already set up correctly, and I do not need to install Intel Math Kernel Library or include intelmkl.redist.win-x64 package, right?
Yes, you need not to install MKL package. You can obtain MKL libraries from other machine which install it.

> I'm a bit confused as I do not see any performance gain when using MKL vs non-MKL packages. I thought I have set up wrongly and the FaceRecognitionDotNet.MKL/DLibDotNet.MKL just fallback to non-MKL when insufficient library/runtime found.

At first, program crashes if mkl libs are missing. right?
Next, MKL depends on intel cpu version, I'm not sure you program can not obtain good performance.
But MKL should incread performance.
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/4
