### ISSUE TITLE
The ability to train my custom model and how to use?

### ISSUE THREAD

**Issue by neonleo** [takuya-takeuchi/FaceRecognitionDotNet#172]
Hi everyone, I have some question about to train my custom model.
My environment is 500 person, each person have 1 to 2  frontal face and well brightness photos.

I have rewrite the tool from HelenTraining to extract the landmark as XML and train to a .dat model file.
everything work fine.

However, when create a FaceRecognition new instanace  - Create(string directory) and I put the custom model mention above to other directory as create() parameter, 
FaceRecognition throw error exception, I have a look on source code, it seem FaceRecognition() only allow to use the default dlib model 

```
if (parameter.PosePredictor5FaceLandmarksModel == null)
                throw new NullReferenceException(nameof(parameter.PosePredictor5FaceLandmarksModel));

            if (parameter.PosePredictor68FaceLandmarksModel == null)
                throw new NullReferenceException(nameof(parameter.PosePredictor68FaceLandmarksModel));

            if (parameter.CnnFaceDetectorModel == null)
                throw new NullReferenceException(nameof(parameter.CnnFaceDetectorModel));

            if (parameter.FaceRecognitionModel == null)
                throw new NullReferenceException(nameof(parameter.FaceRecognitionModel));

```
so my question is, 

is it nessesary to train my own model to get better accuracy?
and how to use my own custom model?
thank you for answer and thanks you for this great project!

**Comment by takuya-takeuchi** [comment]
@neonleo 
You can use `public static FaceRecognition Create(ModelParameter parameter)`

**Comment by neonleo** [comment]
> @neonleo
> You can use `public static FaceRecognition Create(ModelParameter parameter)`

Thank you for help, I will look on this.
And do you suggest I may train my own model or use exist dlib-model ?

**Comment by takuya-takeuchi** [comment]
@neonleo 

>  And do you suggest I may train my own model or use exist dlib-model ?

You can use exist dlib-model like https://github.com/ageitgey/face_recognition_models/tree/master/face_recognition_models/models.

Perhaps, you can train the original data and create custom model.
I only have a faint memory whether dlib example generates proper models from the following

* https://github.com/davisking/dlib/blob/8d4df7c0b3fa7c4c1e4175951161b01ccf4541b5/examples/dnn_mmod_ex.cpp
* https://github.com/davisking/dlib/blob/8d4df7c0b3fa7c4c1e4175951161b01ccf4541b5/tools/archive/train_face_5point_model.cpp
* https://github.com/davisking/dlib/blob/8d4df7c0b3fa7c4c1e4175951161b01ccf4541b5/examples/dnn_face_recognition_ex.cpp

**Comment by neonleo** [comment]
thank you!!
