### ISSUE TITLE
Mac OS 11.4 Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libOpenCvSharpExtern, 1): image not found

### ISSUE THREAD

**Issue by khinklenj** [takuya-takeuchi/FaceRecognitionDotNet#175]
Hi,
I am running Mac OS 11.4 Im getting the following error when trying to run your code
Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libOpenCvSharpExtern, 1): image not found

Thank you
Keith

**Comment by takuya-takeuchi** [comment]
@khinklenj 
Why don't you ask about it on OpenCVShapr repo?
