### ISSUE TITLE
getting "cudaErrorInvalidDeviceFunction"

### ISSUE THREAD

**Issue by jmpangilinan** [takuya-takeuchi/FaceRecognitionDotNet#181]
I'm getting this error

![image](https://user-images.githubusercontent.com/33484940/131246182-40012b15-c876-4d35-a7ba-ffea950b8668.png)

- **`GPU: GT 710`**
- **FaceRecognitionDotNet.CUDA112 1.3.0.4**
- **DlibDotNet.CUDA112 19.21.0.20210302**
- **cuDnn 11.4 v8.2.2.26**
- **CUDA Toolkit 11.2**

Code where error occurs:

`IEnumerable<Location> faceLocations = _faceRecognition.FaceLocations(faceRecognitionImage,1,Model.Cnn);`

Update:

This is working with:

- **DlibDotNet.CUDA101 19.18.0.20200525**
- **FaceRecognitionDotNet.CUDA101 1.3.0.4**
- **cuDnn 10.1 v7.6.5**
- **CUDA Toolkit 10.1**

I'm gonna try 10.2

Update:

Also working with

- **DlibDotNet.CUDA102 19.18.0.20200429**
- **FaceRecognitionDotNet.CUDA102 1.3.0.4**
- **cuDnn 10.2 v7.6.5**
- **CUDA Toolkit 10.2**
- **CUDA Toolkit Patch 10.2.1**
- **CUDA Toolkit Patch 10.2.2**

![image](https://user-images.githubusercontent.com/33484940/131249764-75e2209f-2f2b-4077-b77e-346e059f3228.png)

Not working with **DlibDotNet.CUDA102 19.20.0.20200725** or above.

This is tested with real-time face recognition using `Emgu.CV`, I'm getting around 15-17 fps, 240P resolution, when no face is detected, around 13-14 fps when a face is detected. Compared with MKL, it is exactly the same in performace, but GPU resource is used instead of CPU, which is good. My processor is `i7-9700`. Also in MKL, the CPU resource will reach 100% when it detects a face. I want to test it on a higher GPU, to see if the fps increases.

**Comment by takuya-takeuchi** [comment]
@jmpangilinan 
Do you staill invoke program on GT 710?
GT 710 is legacy gpu.
I'm not sure CUDA 11.2 support GT 710 but it could be ok.

This issue could relate to dlib.
dlib have dropped to support sm 30 since Jul 12, 2020 (23b9abd07a56f9fef560aa9e263b37f82543a0cc).
19.21.0.20210302 corresponds to 9117bd784328d9ac40ffa1f9cf487633a8a715d7.
So FaceRecognitionDotNet.CUDA112 1.3.0.4 does not work on GT 710.

**Comment by jmpangilinan** [comment]
> @jmpangilinan 
> Do you staill invoke program on GT 710?
> GT 710 is legacy gpu.
> I'm not sure CUDA 11.2 support GT 710 but it could be ok.
> 
> This issue could relate to dlib.
> dlib have dropped to support sm 30 since Jul 12, 2020 (23b9abd07a56f9fef560aa9e263b37f82543a0cc).
> 19.21.0.20210302 corresponds to 9117bd784328d9ac40ffa1f9cf487633a8a715d7.
> So FaceRecognitionDotNet.CUDA112 1.3.0.4 does not work on GT 710.
> 
> 

Yes I know it is legacy, it is the only gpu I have for now in office. Btw, what does sm30 mean?

**Comment by takuya-takeuchi** [comment]
sm_xx means that Streaming Multiprocessor.
if sm_50, code requirrs gpu supports Streaming Multiprocessor more than 50.

Basically, sm could equals to cc (compute capability).
So cc_30 seriea were dropped from latest dlib.

**Comment by jmpangilinan** [comment]
I see, thank you for clarifying. Anyways, 

I have now tried this configuration:

- **FaceRecognitionDotNet.CUDA112 1.3.0.4**
- **DlibDotNet.CUDA112 19.21.0.20210302**
- **cuDnn 11.4 v8.2.2.26**
- **CUDA Toolkit 11.2**

on a **GTX 1070**, it really improved the frame rate, even caps my 30 fps 1080p webcam. I scaled down the `FaceRecognition.Image` to 768p, it locks at 30 fps. At 1080p around 27-28fps.
