### ISSUE TITLE
FaceRecognition.FaceLocations() method improvement needed not to use yield return.

### ISSUE THREAD

**Issue by goodmorningsky** [takuya-takeuchi/FaceRecognitionDotNet#182]
public IEnumerable<Location> FaceLocations(Image image, int numberOfTimesToUpsample = 1, Model model = Model.Hog);

 var faceLocations = faceRec.FaceLocations(img);
The above method takes about 4 second on a image.
And when I call  "faceLocations.Count()" it takes another 4 seconds.
(I have to call Count() to avoid further logic in case there is no Face detected.)
Each time, I call any method of IEnumerable, it seems do all routine again.

When I remove "yield return", it works as expected.

Also, the same performance issue occurs for all methods using yield return. 

I like to use Nuget package instead of my own compile. If you improve this, I think it will be great since that's the significant performance bottleneck.

**Comment by takuya-takeuchi** [comment]
@goodmorningsky 
Thank you for your good report.
OK, I will check and try modified code.

BTW, could you provide minimum sample code to measure performance?
I may mistake and it may not work after release.
Thank you for your cooperations.

**Comment by goodmorningsky** [comment]
Here is brief meansure:
var faceLocations = faceRec.FaceLocations(img); // this takes 4 seconds
if(faceLocations.Count() > 0) // this takes 4 seconds.
var arrayOfFaceLocation = faceLocations.ToArray(); //this also takes 4 seconds or little more.


Worst part is related Encoding. Here are my testing.
var faceEncodings = faceRec.FaceEncodings(img, faceLocations, 1); //this takes 33 seconds.
var faceEncodingArray = faceEncodings.ToArray(); //this takes another 33 seconds.
foreach (var faceEncoding in faceEncodings) // "in" takes also 33 seconds.


When I remove the yield return using List<> like below. It works fine.
           List<FaceEncoding> list = new List<FaceEncoding>();
            var rawLandmarks = this.RawFaceLandmarks(image, knownFaceLocation, predictorModel, model);
            foreach (var landmark in rawLandmarks)
            {
                var ret = new FaceEncoding(FaceRecognitionModelV1.ComputeFaceDescriptor(this._FaceEncoder, image, landmark, numJitters));
                landmark.Dispose();
                list.Add(ret);
            }
            return list;

**Comment by takuya-takeuchi** [comment]
@goodmorningsky 
Thanks.
I was able to reproduce your issue and created PR #184
Is it what you intend to?

**Comment by goodmorningsky** [comment]
> @goodmorningsky Thanks. I was able to reproduce your issue and created PR #184 Is it what you intend to?

Yes. Thank you.

**Comment by takuya-takeuchi** [comment]
@goodmorningsky 
We have already release new version 1.3.0.5.
