### ISSUE TITLE
Possible to (de)serialize FaceEncoding class

### ISSUE THREAD

**Issue by Symbai** [takuya-takeuchi/FaceRecognitionDotNet#185]
I'm using this to compare faces from images but I find it very time consuming that each time I have to load the images, create face encodings and then compare it. I would like to be able to store the `FaceEncoding` once I've created it from an image, so I can skip loading image and creating `FaceEncoding` from it next time and just call the compare faces method.

Is this something I can do already? If not, can you provide a way to save/load `FaceEncoding` from/to byte array or simply add a public constructor so we can (de)serialize it ourselves?

**Comment by takuya-takeuchi** [comment]
@Symbai 
You can use `FaceEncoding.GetRawEncoding()` to get data and serialize it.
And `FaceEncoding.LoadFaceEncoding` can deserialize FaceEncoding from double[].

**Comment by Symbai** [comment]
There is no `FaceEncoding.LoadFaceEncoding`, which version do I need? I'm using latest `1.3.0.4`

**Comment by takuya-takeuchi** [comment]
@Symbai 
Sorry. not `FaceEncoding.LoadFaceEncoding` but `FaceRecogniton.LoadFaceEncoding`
