### ISSUE TITLE
Can FaceRecognitionDotNet be used or adapted to recognize animal faces?

### ISSUE THREAD

**Issue by AderitoSilva** [takuya-takeuchi/FaceRecognitionDotNet#186]
If this feature is not already present, would it be possible to include this feature in FaceRecognitionDotNet (well, the means to train it)? Animal facial recognition depends on species and breed. Imagine dog facial detection, for instance: there are many breeds and different looks for each age. Would it be possible to use custom data sets for training these specific facial recognition?

Animal face recognition is very useful for finding missing pets, tagging cattle and tracking wild animals.

**Comment by takuya-takeuchi** [comment]
No. FaceRecognitionDotNet depends on dlib and face_recognition.
They focus on detecting human face.
And I have no methods to train dataset to detect/recognizes animal face.
