### ISSUE TITLE
An object reference is required for the nonstatic field, method 'FaceRecognition.FaceEncodings()'

### ISSUE THREAD

**Issue by Is-2m** [takuya-takeuchi/FaceRecognitionDotNet#188]
I'm new to using FaceRecognitionDotNet and now I'm stuck in the beginning of the way, i got a  CS0120 Error saying (An object reference is required for the nonstatic field, method, or property 'member') in the FaceRecognition.FaceEncodings() method.

here's my code:
`private void button1_Click(object sender, EventArgs e)
        {

            string dir = @"C:\models";

            FaceRecognition.InternalEncoding = Encoding.GetEncoding("shift_jis");
            FaceRecognition fr = FaceRecognition.Create(dir);

            Image imageA = FaceRecognition.LoadImageFile(pb_imgA.ImageLocation);
            Image imageB = FaceRecognition.LoadImageFile(pb_imgB.ImageLocation);

            IEnumerable<Location> locationsA = fr.FaceLocations(imageA);
            IEnumerable<Location> locationsB = fr.FaceLocations(imageB);

            IEnumerable<FaceEncoding> encodingB = FaceRecognition.FaceEncodings(imageB, locationsB);
            IEnumerable<FaceEncoding> encodingA = FaceRecognition.FaceEncodings(imageA, locationsA);

        }

        private void pb_imgA_Click(object sender, EventArgs e)
        {
            OpenFileDialog f = new OpenFileDialog();
            if (f.ShowDialog() == DialogResult.OK)
            {
                pb_imgA.ImageLocation = f.FileName;
                pb_imgA.SizeMode = PictureBoxSizeMode.StretchImage;
            }
                
        }

        private void pb_imgB_Click(object sender, EventArgs e)
        {
            OpenFileDialog f = new OpenFileDialog();
            if (f.ShowDialog() == DialogResult.OK)
            {
                 pb_imgB.ImageLocation = f.FileName;
                pb_imgB.SizeMode = PictureBoxSizeMode.StretchImage;
            }
               
        `
here's the error:
![image](https://user-images.githubusercontent.com/60832546/144619977-98c3fe0e-9344-42fd-ae89-0980c5036364.png)

i tried searching for the causes and solutions for this error but to no avail,  neither my class nor my method is static , but the error is still there. 

if there's any missing information tell me to attach it as well, and please give me some guidance.

**Comment by takuya-takeuchi** [comment]
@Is-2m 
FaceEncoding is not static method.
So you must do

````
IEnumerable<FaceEncoding> encodingB = fr.FaceEncodings(imageB, locationsB);
````

**Comment by Is-2m** [comment]
@takuya-takeuchi
Thanks it worked
