### ISSUE TITLE
Error DlibDotNet.NativeMethods.

### ISSUE THREAD

**Issue by SenyniumX** [takuya-takeuchi/FaceRecognitionDotNet#193]
I am trying to use FRDN and receive the following exception

System.TypeInitializationException: The type initializer for 'DlibDotNet.NativeMethods' threw an exception. ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at DlibDotNet.NativeMethods.LossMetric_anet_type_create()
   at DlibDotNet.NativeMethods..cctor()
   --- End of inner exception stack trace ---

My environnement is as folow 

Windows Server 2019 x64 Processor Intel Core I9 9900K CPU
DotLibDotNet v 19.21.0.20210302
FRDN v 1.3.0.5
Visual C++ 2015-2019 Redistributable 

On my development environment, it works perfectly

Can you help please ?

**Comment by takuya-takeuchi** [comment]
@SenyniumX 
Please check C# project configuration.
I think your project file uses 'Prefer 32bit'.
https://stackoverflow.com/questions/12066638/what-is-the-purpose-of-the-prefer-32-bit-setting-in-visual-studio-and-how-does

**Comment by SenyniumX** [comment]
It works now. You save my day, Thanks a lot
