### ISSUE TITLE
when image.mode = Greyscale  then add Rgb image? 

### ISSUE THREAD

**Issue by falsebo** [takuya-takeuchi/FaceRecognitionDotNet#202]
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/blob/07c359db45dadf7e9d0966104c9fbbe097cb05bf/src/FaceRecognitionDotNet/FaceRecognition.cs#L368

Is this a mistake?

**Comment by takuya-takeuchi** [comment]
@falsebo 
Yes. it should be mistake. But we must check whether it occurs other issue if fix it.

**Comment by takuya-takeuchi** [comment]
Fix
