### ISSUE TITLE
Hello, I did share.

### ISSUE THREAD

**Issue by liuww111** [takuya-takeuchi/FaceRecognitionDotNet#21]
https://www.cnblogs.com/RainbowInTheSky/p/10247921.html 
Thank you for your packing.
Small suggestion：
Errors in using Chinese，I used GB2312，is OK
![image](https://user-images.githubusercontent.com/12441138/50940701-ed59c000-14bc-11e9-8b4b-2efe438ea4d2.png)

**Comment by takuya-takeuchi** [comment]
thanks.

It is not issue of FRDT but DlibDotNet.

This method is called frequency anywhere.
If improve, expose encoding value and user can change it.

````csharp
DlibDotNet.StringEncoding = "gb2312"; // static property
````

**Comment by takuya-takeuchi** [comment]
Hi, I update package to 1.2.3.7.
Could you try the following code in the head of your code?

````csharp
FaceRecognition.InternalEncoding = System.Text.Encoding.GetEncoding("gb2312");

...
````

This property changes encoding which convert System.String to byte[] in DlibDotNet.
It could work.

**Comment by HEYRIX** [comment]
@liuww111 May you please help to fix some issue on using this library? Thanks.
