### ISSUE TITLE
Could not copy the file "\packages\FaceRecognitionDotNet.1.3.0.7\runtimes\win-AnyCPU\native\DlibDotNetNativeDnnAgeClassification.dll" because it was not found.

### ISSUE THREAD

**Issue by salmana66** [takuya-takeuchi/FaceRecognitionDotNet#212]
Hi, 
I'm trying to use this library in my application and i'm getting this build error. I would really appreciate if someone Please help me fix this problem. I have attached a screenshot for your reference.
**cc: @takuya-takeuchi** 

Thank you

<img width="427" alt="Error" src="https://user-images.githubusercontent.com/11440531/186634572-e3ff5b55-8585-4ff7-9e7b-43dcabba2d26.png">

**Comment by takuya-takeuchi** [comment]
@salmana66 
It is not bug.
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/wiki/Quickstart#warning-warning-for-visual-studio-users

I'm not planning to support any-cpu because nuget package should be more larger.

**Comment by salmana66** [comment]
Okay i got it @takuya-takeuchi , can you please suggest to which platform should we target our project? i mean which one is better and works better with this library, x86 or x64?

**Comment by takuya-takeuchi** [comment]
You should choise x64.
I'm not sure x64 cpu is better than x86 in the point of view pf architecture.
But x64 program can allocate huge memory.
It should make stable program.
Espeicailly, model file take large memory. We would avoid out of memory by choise x64.

**Comment by salmana66** [comment]
Sure thing @takuya-takeuchi , Thank you very much!
