### ISSUE TITLE
 UnhandledException: System.TypeInitializationException: The type initializer for 'DlibDotNet.NativeMethods' threw an exception.

### ISSUE THREAD

**Issue by maoshanli** [takuya-takeuchi/FaceRecognitionDotNet#222]
I get the references by nuget package, the DlibDotNet version is 19.21.0.20220724.It works well on my machine, my os is win10,64 bit, the cpu is intel core i7-7700 cpu. The Target framework of my program is .net core 3.1. The program was published as 
independent ,both win-x86 and win-x64. On my machine, the win-86 and win-x64 can work well. When I deploy the program on server ,the error  appears as follow:
UnhandledException: System.TypeInitializationException: The type initializer for 'DlibDotNet.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'DlibDotNetNativeDnn' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
   at DlibDotNet.NativeMethods.LossMetric_anet_type_create()
   at DlibDotNet.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at DlibDotNet.NativeMethods.get_frontal_face_detector()
   at DlibDotNet.Dlib.GetFrontalFaceDetector()
The cpu of my server is Intel(R) Xeon(R) Platinum 8163,the  os is Microsoft Windows Server 2019 Datacenter.I have tried both  win-x86 and win-x64,the problem exist.
I have scanned the related issues like #172, the nuget package was setted to  v19.17.0.20190813, the problem still exist.
Please let me know how i can correct this

Thanks

**Comment by maoshanli** [comment]
sorry, I set the package to  v19.17.0.20190813  is another problem , and I have solved this by referencing to #136 on my machine,x64 works well,but on my server the problem still exist.

**Comment by takuya-takeuchi** [comment]
@maoshanli 
Please clarify problem you face.

* Why did you install old nuget package? You should use latest package unless you use legacy cpu machine
  * And you need not install DlibDotNet manually.
* 0x8007007E may be caused by https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/47 or https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/122

**Comment by maoshanli** [comment]
Thank you for your reply.I reference the issue #122, I know the problem. The C++ related dll are not included.Thank you very much.
