### ISSUE TITLE
How to realize in real time face detection?

### ISSUE THREAD

**Issue by jakkielong** [takuya-takeuchi/FaceRecognitionDotNet#23]
Sorry, I have a question for FaceRecognitionDotNet. As far as I know, for python we could use "ret, frame = video_capture.read()" to get frame and input into face_locations to realize real time detect.
For FaceRecognitionDotNet, we have to nominate the specific image path, sorry for my stupid, I tried a lot of times, still can not find a good way to input bytes or array , or transfer bytes or array into  Image into FaceLocations instead of image path .Please author can answer my question. thanks

**Comment by takuya-takeuchi** [comment]
Do you want to transfer byte[] to Image class?
You can use LoadImage method.

But this method accept only raw image byte data.
You can not pass image file byte data.

**Comment by jakkielong** [comment]
Hi takuya,
Thanks for your prompt reply. really appreatite to answer my next quesiton 
bmp = new RenderTargetBitmap((int)vce1.ActualWidth, (int)vce1.ActualHeight, 96, 96, PixelFormats.Default);
                bmp.Render(vce1);
                encoder = new JpegBitmapEncoder();
                encoder.Frames.Add(BitmapFrame.Create(bmp));
using (MemoryStream ms = new MemoryStream())
                {encoder.Save(ms);
                data = ms.ToArray();}
when I use above codes to capture image from WPF, and save to data variable. 
As your suggestion, to use loadimage function. what is row and column needs to input?
 FaceRecognition.LoadImage(data, ?, ?,3)

**Comment by takuya-takeuchi** [comment]
row is height and cols is width.
but widows bitmap data include padding.
so width x height x 3 != data.Length, perhaps.

**Comment by jakkielong** [comment]
yes, it is !=
then, do you have any good suggestions to do real time face recognition without saving image to path. 
I use WPF to design frontend can using above codes to catch image bytes.
or, do we have any method to get specific row and column of bitmap for LoadImage

**Comment by takuya-takeuchi** [comment]
You created already BitmapSource from BitmapFrame.Create(bmp). So you can manipulate raw image data from it. Maybe you can refer the following code (Not test)

````sharp
int stride = (width  * (channels * 8 + 7)) / 8;
var buffer = new byte[stride];
var output = new byte[width * height * channels];
fixed(byte* po = &output[0])
fixed(byte* pb = &buffer[0])
{
   var p = po;
   for (int y = 0; y < height; y++)
   {
      roi.Y = y;
      bitmapSource.CopyPixels(roi, (IntPtr)pb, stride, stride);
      Marshal.Copy(pb, output, width * channels * y, width * channels)
   }
}
````

After this, you can pass output to LoadImage method. Do i understand what you mean?

**Comment by jakkielong** [comment]
Another question, do you have any good idea to deal with long distance and small face detection?
eg: magnify and clarify face, do we have this function in this program?

**Comment by takuya-takeuchi** [comment]
Create many face encoding data which are extracted from small face image of target person. And use them for small detected face image while matching. You can decide exact person by knn, average of all matching, etc.

However, far face image has a tendency to occur false negative hit.
I think it is one way to give up about low quality face image.

**Comment by jakkielong** [comment]
thanks, I could run it successfully. But there is a new problem when I train the FaceEncodings, it is too slow. I know we can use command to input gpu or cpu numbers to make fasters, can we not use command to define cpu and gpu, there is any way to define by function.

**Comment by takuya-takeuchi** [comment]
FaceRecognitionDotNet\test\FaceRecognitionDotNet.Tests include serialize and deserialize test. It works fine now.
Could you show me your code?

**Comment by takuya-takeuchi** [comment]
No. As far as using nuget FaceRecognitionDotNet package, you need not to install it.
But if you want to custom DlibDotNet for embedding intel mkl, you have to install it and compile DlibDotNet.

**Comment by jakkielong** [comment]
| Name | Value | Type
-- | -- | -- | --
▶ | $exception | {System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)    at DlibDotNet.NativeMethods.get_frontal_face_detector()    at FaceRecognitionDotNet.FaceRecognition..ctor(String directory)    at FaceRecognitionDotNet.FaceRecognition.Create(String directory)    at BBACFACE.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) in C:\Code\FaceShow1.0\BBACFACE\BBACFACE\MainWindow.xaml.cs:line 36    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)    at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)    at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)    at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)    at MS.Internal.LoadedOrUnloadedOperation.DoWork()    at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()    at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()    at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)    at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)    at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)    at System.Windows.Interop.HwndTarget.OnResize()    at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)    at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)} | System.BadImageFormatException

**Comment by takuya-takeuchi** [comment]
> I got a new problem that was not happened before.

What did you do on this time? I can not understand from this information.

But you should check the following things.

* Application works as 64bit or not
* DlibDotNet.Native and DlibDotNet.Native.Dnn are 64bit or not if you built them yourself

BadImageFormatException occurs by mismatch of application architecture between exe and dll.

**Comment by takuya-takeuchi** [comment]
No response

**Comment by cucr** [comment]
> thanks, I could run it successfully. But there is a new problem when I train the FaceEncodings, it is too slow. I know we can use command to input gpu or cpu numbers to make fasters, can we not use command to define cpu and gpu, there is any way to define by function.

hello,I have the same problem when i use wpf-mediakit. whether you can provide subsequent code of how to use 
LoadImage(Byte[], Int32, Int32, Int32, Mode)
thanks.
