### ISSUE TITLE
Not Find ProjectDlibDotNet 

### ISSUE THREAD

**Issue by HuaFangYun** [takuya-takeuchi/FaceRecognitionDotNet#237]
![image](https://github.com/takuya-takeuchi/FaceRecognitionDotNet/assets/30250585/8de9aed2-36e8-4ef4-a4e6-162f6d6ae7b5)

**Comment by Sl0thie** [comment]
You can manually copy the source from the authors other repository https://github.com/takuya-takeuchi/DlibDotNet to solve this issue.
