### ISSUE TITLE
Question: Is FaceRecognition class Thread safe

### ISSUE THREAD

**Issue by luchunminglu** [takuya-takeuchi/FaceRecognitionDotNet#25]
does static method in FaceRecognition class thread safe?

**Comment by takuya-takeuchi** [comment]
I believe so.
do you face any issue? if so, please report!
Thank you for your cooperations.

**Comment by takuya-takeuchi** [comment]
What you are talking about FaceEncoding means that there is problem on static method using FaceEncoding, right?
Do you know which methods is not thread safe?

**Comment by takuya-takeuchi** [comment]
OK. I understand what you say. And I misunderstood.

Yes. FaceEncodings method is not thread safe. But it is specification.
FaceRecognition instance has ShapePredictor, LossMmod and FrontalFaceDetector.
These members contains DNN network.

So if application access to these member from mult-threads, they could corrupt network.

Therefore, you must create 2 FaceRecognition instance.
