### ISSUE TITLE
People does not notice FaceEncoding class support serialization

### ISSUE THREAD

**Issue by takuya-takeuchi** [takuya-takeuchi/FaceRecognitionDotNet#27]
Should I implement?

* FaceRecognition.Save method
  * FaceRecognition.LoadEncoding https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/14#issuecomment-466039286
* FaceEncoding.Save method
  * If it implement, developer would require how to load from file.

**Comment by Hershef** [comment]
This is needed very much.

**Comment by pierresa** [comment]
Yes absolutly !! it is a must!

thank you 
Pierre

**Comment by takuya-takeuchi** [comment]
@pierresa 
Now, FR provide LoadFaceEncoding. So I will provide 

````cs
public static void SaveFaceEncoding(FaceEncoding, string path);
````

It generates file of raw float array data.

Thanks.

**Comment by danijerez** [comment]
Is SaveFaceEncoding available?

**Comment by takuya-takeuchi** [comment]
@danijerez 
I just answered your question on https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/135#issuecomment-683409850

**Comment by takuya-takeuchi** [comment]
I proviede GetRawEncoding method.
So I will NOT provide SaveFaceEncoding.
close.
