### ISSUE TITLE
nuget package is missing native dlls?

### ISSUE THREAD

**Issue by antongit** [takuya-takeuchi/FaceRecognitionDotNet#33]
Hello @takuya-takeuchi,

thank you so much on your work on wrapping dlib.
It's amazing.

I've just noticed, that the nuget package for the FaceRecognitionDotNet doesn't include native
* DlibDotNetNative.dll
* DlibDotNetNativeDnn.dll

The DlibDotNet has these packages.

Am I doing something wrong? My machine complains, that it can't find these two dlls.
What will be a workaround if you didn't include these native dlls intentionally?

Best,
Anton

**Comment by takuya-takeuchi** [comment]
@anton
DaceRecognitionDotNet depends on DlibDotNet.
Hence, FRDN needs not to include Dlib*.

Do you face to build or runtime issue?
If so, please tell me about your machine info, eg. os, x64 or not, .net version.

**Comment by antongit** [comment]
Thank you for your quick reply.
I've just tested once again on another machine and everything works fine here.
Probably I have some dll-hell on the machine I've tested it first. Will have to investigate there.

I'm on x64, .NET Framework 4.7.2.
It was a runtime issue during calling the FaceRecognition.Create().
Never mind, the problem is on my side.

Best wishes and thanks again for your work!
Anton
