### ISSUE TITLE
Compatible with Xamarin?

### ISSUE THREAD

**Issue by Sethayla** [takuya-takeuchi/FaceRecognitionDotNet#35]
I am wondering if the FaceRecognitionDotNet nuget package is compatible with Xamarin? 
Running the application in a console app it all works fine, but running it in a Xamarin app (Xamarin Forms, but deploying it on Android) the following error occurs:

Running: 
   faceRecognition = FaceRecognition.Create(directoryInfo.FullName);

gives the following error:

   System.DllNotFoundException:  DlibDotNetNative

But the Dll's are in the output folders:
![image](https://user-images.githubusercontent.com/48485934/54212092-b450c280-44e2-11e9-8319-d508dd0d263f.png)

It seems like the dll's are not included in the .sdk file.
Which is where it is looking for the libraries I suppose.

**Comment by Sethayla** [comment]
Creating it with UWP (universal windows) works fine. So creating the correct sdk might be a problem?

**Comment by takuya-takeuchi** [comment]
android works on arm device.
and FRDN and DlibDotNet are not available on.

Please refer #29

**Comment by Lotusv** [comment]
I'm tested FRDN ARM, it installed but still get error dlibdotnetnative, is ARM required these dlls and which format for xamarin android project?

**Comment by takuya-takeuchi** [comment]
No. I guess you want to use FRDN on iOS or android. But these binary must be built with additional setting.
FRDN ARM and DlibDotNet ARM are not build for iOS and Android.

I had tried build for iOS and Android.
https://github.com/takuya-takeuchi/DlibDotNet/blob/master/nuget/BuildAndroid.ps1
https://github.com/takuya-takeuchi/DlibDotNet/blob/master/nuget/BuildOSX.ps1

But binary size became too large, over 100MB. It could violate regulation of each Store.
Fow now, iOS and Android support is low priolity.

I guess some developer will claim about performance if I support them.
I doubt FRDN (DlibDotNet DNN function) works fine with moderate performance.
