### ISSUE TITLE
[Suggestion] CompareFace(s) return float replace bool.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [takuya-takeuchi/FaceRecognitionDotNet#37]
May be return float is more flexible.
For example, `CompareFaces` return more than one `true` element.

**Comment by takuya-takeuchi** [comment]
I understand what you hope.
I think you can use FaceDistance method to achieve what you hope.
TBH, I agree with you because CompareFaces is a bit complex to use.

````csharp
var score = new List<double>();
foreach (var target in databaseFaces)
{
    score.Add(FaceRecognition.FaceDistance(target, searchFace));
}
````

**Comment by takuya-takeuchi** [comment]
P.S.
Are you Japanese? If so, you can use Japanese here.
Your name looks like to be Japanese name.

**Comment by MiyamuraMiyako** [comment]
Sorry, I'm Chinese, I love Japan ACG, so I used the name of this anime character.

You are right, `FaceDistance(s)` suitable for my requirements.

**Comment by takuya-takeuchi** [comment]
Oh, I'm very sorry.
Your icon is so cute.

Thank you for interesting this product and Japan ACG!!!
