### ISSUE TITLE
Is any plan to encapsulation biopsy function.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [takuya-takeuchi/FaceRecognitionDotNet#38]
Is any plan to encapsulation biopsy function.(e.g. eye blink).

**Comment by takuya-takeuchi** [comment]
No. FRDN is porting library from face_recognition.
FRDN only aims to become C# library of face_recognition.

I don't know encapsulation biopsy.
Is there any oss library?

**Comment by MiyamuraMiyako** [comment]
Ok, I understand.

Biopsy let people make some facial movements (such as eye blinking, turning heads etc.)  to prevent the use of photos by detecting.

**Comment by takuya-takeuchi** [comment]
No response
