### ISSUE TITLE
Can I open these projects in VS2015?

### ISSUE THREAD

**Issue by zuluck2004** [takuya-takeuchi/FaceRecognitionDotNet#39]
My office environment only have the VS2015, and at current I don't want to upgrade to VS2017.
But when I open the  solution FaceRecognitionDotNet in the VS2015, the projects always loaded fail.
The error as following:
"FaceEncodingPerformance.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format."
I have install the .net core sdk2.2 and the nuget.exe 3.6.0. But I still can't work. 
Is it really the .net standard2.0 project can't load in the vs2015?

**Comment by takuya-takeuchi** [comment]
This almost of this project are created by .net core application.
MSFT says that .net core application is developed by VS 2017.
https://docs.microsoft.com/ja-jp/dotnet/core/windows-prerequisites?tabs=netcore2x

But you can build and run without VS IDE.
You can use your favorite editor and type the following command

````
dotnet build -c Release
````

or 

````
dotnet run -c Release
````

**Comment by zhengshuangstar** [comment]
> This almost of this project are created by .net core application.
> MSFT says that .net core application is developed by VS 2017.
> https://docs.microsoft.com/ja-jp/dotnet/core/windows-prerequisites?tabs=netcore2x
> 
> But you can build and run without VS IDE.
> You can use your favorite editor and type the following command
> 
> ```
> dotnet build -c Release
> ```
> or
> 
> ```
> dotnet run -c Release
> ```

Thanks for the reply. I will have a try.

**Comment by zhengshuangstar** [comment]
> > This almost of this project are created by .net core application.
> > MSFT says that .net core application is developed by VS 2017.
> > https://docs.microsoft.com/ja-jp/dotnet/core/windows-prerequisites?tabs=netcore2x
> > But you can build and run without VS IDE.
> > You can use your favorite editor and type the following command
> > ```
> > dotnet build -c Release
> > ```
> > or
> > ```
> > dotnet run -c Release
> > ```
> 
> Thanks for the reply. I will have a try.

Yes, using the following command is OK. I can run the example without the vs2017.
Thank you very much.
