### ISSUE TITLE
Emgucv&OpencvSharp

### ISSUE THREAD

**Issue by Hummel-Wang** [takuya-takeuchi/FaceRecognitionDotNet#40]
Hi:
   Thank you for providing such a good lib.
   I retrieve the video frame by emgucv and opencvsharp, want to use the same idea to detect faces also. But i don`t got  datas of the type DlibDotNet.Rectangle[] on opencvsharp, What should I do? The code is as follows：
`

        public System.Drawing.Image FaceRecognize(Mat imageFrame)
        {
            System.Drawing.Image bi = null;
            Mat tempImg = imageFrame;
            byte[] array = tempImg.ToBytes();
            System.Drawing.Image image = byteToImage(array);
            BitmapImage bImg = BitmapToBitmapImage(BytesToBitmap(imageFrame.ToBytes()));

            Mat grayImage = new Mat();
            Cv2.CvtColor(tempImg, grayImage, ColorConversionCodes.RGB2GRAY);
            Cv2.EqualizeHist(grayImage, grayImage);

            using (var imageArray = Dlib.LoadImageData<byte>(grayImage.ToBytes(), (uint)bImg.PixelHeight, (uint)bImg.PixelWidth, (uint)bImg.PixelWidth))
            {
                DlibDotNet.Rectangle[] faces = faceDetector.Operator(imageArray);

                foreach (var item in faces)
                {
                    Dlib.DrawRectangle(imageArray, item, new RgbPixel(0, 0, 255));
                }
            }
            bi = byteToImage(imageFrame.ToBytes());
            return bi;
        }`

**Comment by takuya-takeuchi** [comment]
FaceRecognitionDotNet uses FrontalFaceDetector.
But FRDN engancements image before calling FrontalFaceDetector.
And FRDN requires RGB image rather than grayscale.

**Comment by Hummel-Wang** [comment]
Thanks for your reply.
I have used FaceRecognize before calling Dlib.GetFrontalFaceDetector() and Assign to faceDetector.
I  try to use RBG image,but i don`t got datas of the type DlibDotNet.Rectangle[] on opencvsharp.
I tried to debug in Emgucv and OpencvSharp, and don`t found out different in FaceRecognitionDotNet source code. 
![compare](https://i.loli.net/2019/04/08/5caabaa536fff.jpg)

**Comment by Hummel-Wang** [comment]
I`m so sorry.
I didn't go into the source code before. Now, i found out returned value is different on GetSize function in StdVector class. The retruned value is zero when used opencvsharp. so where is the problem? I don't know how to fix it. pls tell me the reason why there might be a problem, I'll try to solve it. thank you very much.
![reson](https://i.loli.net/2019/04/08/5caac3d0504d2.jpg)

**Comment by takuya-takeuchi** [comment]
Emgucv works, right?
Opencv align image pixel as bgr.
So your emgucv treats mat as bgr and converting to grayscale leads good result.

**Comment by takuya-takeuchi** [comment]
No response
