### ISSUE TITLE
Why BottomLip have 12 points?

### ISSUE THREAD

**Issue by MiyamuraMiyako** [takuya-takeuchi/FaceRecognitionDotNet#42]
I search dlib 68 point picture, bottom lip only have 8 points.
![图片](https://user-images.githubusercontent.com/10345361/56283101-551a4980-6143-11e9-950b-cdf243caa3c0.png)
![图片](https://user-images.githubusercontent.com/10345361/56282958-ff45a180-6142-11e9-84a7-41ccf9442d70.png)

**Comment by takuya-takeuchi** [comment]
49, 61, 65 and 55 are belonged to bottom lips.

**Comment by MiyamuraMiyako** [comment]
It's means 49,61,65,55 belongs to top lip and bottom lip?

**Comment by takuya-takeuchi** [comment]
yes

**Comment by takuya-takeuchi** [comment]
Wait. I cannot remember why did I decide that two 12 point are lips.
I do not have research or document.

**Comment by takuya-takeuchi** [comment]
Oh, I found.
Please refer https://github.com/ageitgey/face_recognition/blob/master/face_recognition/api.py

**Comment by MiyamuraMiyako** [comment]
Ok, thanks a lot!
