### ISSUE TITLE
Efficient way to LoadImage from OpenCVSharp

### ISSUE THREAD

**Issue by utarn** [takuya-takeuchi/FaceRecognitionDotNet#44]
I got a Mat object from OpenCVSharp. How do I efficiently load the image to 
 FaceRecognition.LoadImage or should I use DlibDotNet to load an image?

Thanks

**Comment by takuya-takeuchi** [comment]
You can refer https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/40
He noted sample source code to load from OpenCVSharp.

**Comment by utarn** [comment]
Sorry takuya-takeuchi, I'm still not getting the reference.
I got a cropped grayscale Mat from opencvsharp as I use haarcascade to do a rough detect.
I also tried

```
   var array = new byte[source.Height * source.Width];
            source.GetArray(source.Width, source.Height, array);
            var image = FaceRecognition.LoadImage(array, source.Height, source.Width, 1);
```

**Comment by takuya-takeuchi** [comment]
Last argument of LoadImage is not 1. It is stride. stride is width * channels.
So it is width * 1 if grayscale.

**Comment by takuya-takeuchi** [comment]
Oh, sorry. You are correct. Last argument is element size.

**Comment by utarn** [comment]
But still I got ArrayOutOfRangException. So I tried
```
 var array = new byte[source.Height * source.Width];            
            source.GetArray(source.Rows-1, source.Cols-1, array);
            var image = FaceRecognition.LoadImage(array, source.Height, source.Width, 1);
            var encodings = faceRecognition.FaceEncodings(image).ToArray();
```
But the encodings.Length is 0.

**Comment by takuya-takeuchi** [comment]
Could you check the following sample? I wrote sample project using OpenCVSharp.
It may be helpful.
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/tree/develop/examples/OpenCVSharpSample

**Comment by utarn** [comment]
Thank you so much. It worked!
