### ISSUE TITLE
1.2.3.11 Nuget?

### ISSUE THREAD

**Issue by turowicz** [takuya-takeuchi/FaceRecognitionDotNet#45]
I see https://www.nuget.org/packages/FaceRecognitionDotNet/ is outdated.

**Comment by takuya-takeuchi** [comment]
Now, there are not high priority issue.
And on development and developed

* feature/knn (on Development)
* helen dataset support (DONE)
* DlibDotNet update (Unit test is already PASS)
  * but it is major update and it should be carefully

Do you have any idea or feature request?

**Comment by turowicz** [comment]
ok
