### ISSUE TITLE
Potential bug - DlibDotNet

### ISSUE THREAD

**Issue by Lucashglund** [takuya-takeuchi/FaceRecognitionDotNet#46]
Hi there!

Inside the DlibDotNet folder -> Matrix -> Matrix.cs it seems to be a mistake, or I might not understand the purpose with this line of code. 

At line 197 there is an if statement inside the function public Matrix(byte[] array, int row, int column, int elementSize)

**if**(column <1) **do** throw new arg (ElementSize) "should be more than 1".

Shouldn't it instead be **if**(elementSize < 1) **do** throw new arg (ElementSize) "should be more than 1".

If this isn't a bug, could u explain why this is a "Throw new exception" because the line over is stating a similar statement "if(column < 0)" 

Kind regards Lucas

**Comment by takuya-takeuchi** [comment]
@Lucashglund Thank you for reporting bug issue.
Yes, you are right. Condition and message are wrong.
So it should be

````
if (elementSize < 1)
    throw new ArgumentOutOfRangeException($"{nameof(elementSize)} should be greater than or equal to 1.");
````
