### ISSUE TITLE
Error When Use CUDA: Unable to load DLL 'DlibDotNetNativeDnn' or one of its dependencies

### ISSUE THREAD

**Issue by chrishaly** [takuya-takeuchi/FaceRecognitionDotNet#47]
A simple test to getting face location by Model.Cnn occurred errors when use package FaceRecognitionDotNet.CUDA100.

> System.DllNotFoundException: 'Unable to load DLL 'DlibDotNetNativeDnn' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)'

Code at git repo https://github.com/chrishaly/FaceDetectionCudaTest

Reproduce:

1. Create a project with contents:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FaceRecognitionDotNet.CUDA100" Version="1.2.3.12" />
  </ItemGroup>

  <ItemGroup>
    <None Update="input.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
```

2. Add code to Program.cs as
```csharp
using System;
using System.Linq;
using FaceRecognitionDotNet;

namespace FaceDetectionCuda
{
    class Program
    {
        private static FaceRecognition _faceRecognition;

        static void Main(string[] args)
        {
            var modelDirectory = @"D:\dev\dlib-model";
            _faceRecognition = FaceRecognition.Create(modelDirectory); //Exception

            var src = @"input.jpg";
            using (var imageSrc = FaceRecognition.LoadImageFile(src))
            {
                var faceLocations = _faceRecognition.FaceLocations(imageSrc, 0, Model.Cnn).ToArray();
                var faceEncodings = _faceRecognition.FaceEncodings(imageSrc, faceLocations).ToArray();
                Console.WriteLine($"Face count: {faceEncodings.Length}");
            }
        }
    }
}
```

3. when run to FaceRecognition.Create exception throws:
> System.DllNotFoundException: 'Unable to load DLL 'DlibDotNetNativeDnn' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)'

However after change package FaceRecognitionDotNet.CUDA100 to package FaceRecognitionDotNet all run correct.

**Comment by takuya-takeuchi** [comment]
My dev machine does not install dotnet 2.2 sdk.
So I modified program.cs and csproj

* var modelDirectory
` netcoreapp2.0 to netcoreapp2.2

And then, I execute the program by the following

````
dotnet run -c Release
Face count: 3
```

I guess you do not install CUDA 10.0.

CUDA_PATH need not to specify CUDA 10.0.
The following is my dev machine's env values.

````
set CUDA
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2
CUDA_PATH_V10_0=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
CUDA_PATH_V9_0=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0
CUDA_PATH_V9_1=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1
CUDA_PATH_V9_2=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2
````

Could you check whether CUDA_PATH_V10_0 is.

**Comment by chrishaly** [comment]
@takuya-takeuchi 
Your are right, I was just installed CUDA 10.1.
After install 10.0 it's working right now.
Thanks

**Comment by KoakiMiku** [comment]
I have the same problem, but I installed CUDA 10.0 and 10.1.

> Unable to load DLL 'DlibDotNetNativeDnn' or one of its dependencies: 找不到指定的模块。 (Exception from HRESULT: 0x8007007E)

> set CUDA
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
CUDA_PATH_V10_0=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
CUDA_PATH_V10_1=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1

> nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:04_Central_Daylight_Time_2018
Cuda compilation tools, release 10.0, V10.0.130

**Comment by chrishaly** [comment]
> Unable to load DLL 'DlibDotNetNativeDnn' or one of its dependencies: 找不到指定的模块。 (Exception from HRESULT: 0x8007007E)


the same environment variables on my pc
```
set CUDA
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
CUDA_PATH_V10_0=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
CUDA_PATH_V10_1=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
```

You may have a try with project https://github.com/chrishaly/FaceDetectionCudaTest

**Comment by takuya-takeuchi** [comment]
@KoakiMiku, @chrishaly 
Do you deploy cudnn library to cuda directory?

**Comment by KoakiMiku** [comment]
@takuya-takeuchi  Do you mean CUDA_PATH_V10_0 and CUDA_PATH_V10_1 ?

![image](https://user-images.githubusercontent.com/34326561/63441662-5ac2cb80-c464-11e9-9e8d-6696c16dc298.png)

![image](https://user-images.githubusercontent.com/34326561/63442053-00763a80-c465-11e9-9c19-cafad4b76634.png)

![image](https://user-images.githubusercontent.com/34326561/63442218-50550180-c465-11e9-970f-33abd89cac6a.png)

**Comment by KoakiMiku** [comment]
@chrishaly  Thanks, but still the same problem...

**Comment by KoakiMiku** [comment]
@takuya-takeuchi @chrishaly
Oh... I didn't deploy cudnn library.
It works! Thanks!
