### ISSUE TITLE
FaceEncodings too slow

### ISSUE THREAD

**Issue by eren186** [takuya-takeuchi/FaceRecognitionDotNet#49]
hi @takuya-takeuchi 
     frist thanks for your work.
     i get img from web camera and FaceEncoding it but too slow.
i save one img and use this code to test
it will take about 5000ms to FaceEncoding.
is the img size too big or what ?
(win10 64 i7 6700)
   ` 
Stopwatch getTime = new Stopwatch();
            Image im = FaceRecognition.LoadImageFile("1,jpg");
            getTime.Start();
            FaceEncoding[] array2 = fr.FaceEncodings(im).ToArray<FaceEncoding>();
            getTime.Stop();
            textBox2.Text = getTime.ElapsedMilliseconds + "\r\n";
`

![1](https://user-images.githubusercontent.com/48199905/58847872-0276fb80-86b7-11e9-93ec-910c4f2c928f.jpg)

**Comment by takuya-takeuchi** [comment]
Please check https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/4

On benchmark, FRDN and original puthon code, they can not achieve the high speed on very large image. This image is more largerer than 1080p. so it could be slow.

**Comment by takuya-takeuchi** [comment]
No Response
