### ISSUE TITLE
kernel32

### ISSUE THREAD

**Issue by longas1232** [takuya-takeuchi/FaceRecognitionDotNet#50]
Hello takuya-takeuchi, I reminded you that I needed kernel32.dll when building the project.
Where can I get it, please? Thank you.

**Comment by takuya-takeuchi** [comment]
kernel32.dll is components of windows.
FRDN is managed application. So it does not require kernel32.dll  when building.

Could you show me the following information?

* Visual Studio Version
* Windows Version
* Installed .NET Core SDK  versions
* screen shot presents error message (if you can)

**Comment by longas1232** [comment]
Thank you. takuya-takeuchi
this problem has been solved
I would like to ask a different question. For example, in the process of identification, I entered three faces, but I may mistake one face for another face. Is there any good way to optimize this problem? Well, for example, adjusting parameters and the like. .

**Comment by takuya-takeuchi** [comment]
Create multiple feature data per 1 person. And compare entered face with them.
Then 

* check average score from one person and adapt best average score from all person
* check best score from one person and adapt best average score from all person

Maybe, it's not bad.

**Comment by longas1232** [comment]
Ok, thank you very much, I will try it, there is another problem. Can the existing API circle the faces in the picture and draw a rectangle like the example you gave, the characters in those photos.

**Comment by takuya-takeuchi** [comment]
No. Current DlibDotNet does not support function to draw circle.
It is implemented in dlib as draw_solid_circle.
But DlibDotNet does not use.

**Comment by longas1232** [comment]
Oh, oh, I understand, thank you, can the rectangle be, or all the square shapes will not work?

**Comment by takuya-takeuchi** [comment]
You can use `Dlib.DrawRectangle`

**Comment by takuya-takeuchi** [comment]
No response
