### ISSUE TITLE
TypeInitializationException  the type initializer for "FaceRecognitionDotNet" threw an exception

### ISSUE THREAD

**Issue by zlyxm** [takuya-takeuchi/FaceRecognitionDotNet#51]
hi, I am running a TypeInitializationException error on some computers.
I found that if I didn't install visual studio (2019) on my computer, I would get an error.
After installing the C# programming environment, it will run normally, but it will still run normally after uninstalling visual studio completely. Can you help me see what is going on?

Environment: 64-bit win7 and win10
Release: 64 bit

Thank you

![TIM截图20190617145542](https://user-images.githubusercontent.com/27178240/59590144-fad73e00-911d-11e9-9e62-4e7c395fdc07.png)

**Comment by takuya-takeuchi** [comment]
It is similar with https://github.com/takuya-takeuchi/DlibDotNet/issues/83

**Comment by takuya-takeuchi** [comment]
> I found that if I didn't install visual studio (2019) on my computer, I would get an error.
After installing the C# programming environment, it will run normally, but it will still run normally after uninstalling visual studio completely. Can you help me see what is going on?

FaceRecognitionDotNet depends on DlibDotNet. It depends on Visual C++ 2017 Redistribution.
Maybe, it may be uninstalled after uninstall VS.

You can download redistribution from here
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by zlyxm** [comment]
Yes! It has been tested, thank you !
