### ISSUE TITLE
Increase face recognition accuracy

### ISSUE THREAD

**Issue by code861** [takuya-takeuchi/FaceRecognitionDotNet#56]
This is not an issue. I just need a suggestion. I've used your code to extract face encodings from some images by this code

`

                        foreach (Mat mat in FaceList)
                        {

                            var bytes = new byte[mat.Rows * mat.Cols * mat.ElementSize];
                            Marshal.Copy(mat.DataPointer, bytes, 0, bytes.Length);
                            using (Image img = FaceRecognitionDotNet.FaceRecognition.LoadImage(bytes, mat.Rows, mat.Cols, mat.ElementSize))
                            {
                                lstFaces.Add(new KeyValuePair<string, FaceEncoding>("John" + labelindex, StaticFunctions._faceRecog.FaceEncodings(img, (IEnumerable<Location>)null, 0).FirstOrDefault<FaceEncoding>()));
                                labelindex++;
                            }
                        }`

`FaceList` is a list of images which have faces and the encoding is added to `lstFaces` and this encoding is converted to `array1` and recognition is done like this:
`

                if (StaticFunctions._faceRecog != null)
                {
                    if (_negetiveSample > 10)
                    {
                        RecognitionFailed?.Invoke(this, new EventArgs());
                        logger.WriteLog("Frame Count" + FrameCount, "Info");

                    }
                    if (_postiveSample > 5)
                    {
                        RecognitionCompleted?.Invoke(this, new RecognitionEventArgs() { faceLbl = _positiveLabel });
                        logger.WriteLog("Frame Count" + FrameCount, "Info");
                    }

                    if (!_isFrameProcessing)
                    {
                        _isFrameProcessing = !_isFrameProcessing;
                        var bytes = new byte[mat.Rows * mat.Cols * mat.ElementSize];
                        Marshal.Copy(mat.DataPointer, bytes, 0, bytes.Length);
                        using (Image image1 = FaceRecognitionDotNet.FaceRecognition.LoadImage(bytes, mat.Rows, mat.Cols, mat.ElementSize))
                        {
                            int _faceCount = StaticFunctions._faceRecog.FaceLocations(image1, 1, Model.Hog).Count();
                            if (_faceCount == 1)
                            {
                                foreach (Location faceLocation in StaticFunctions._faceRecog.FaceLocations(image1, 1, Model.Hog))
                                {
                                    FaceEncoding[] array2 = StaticFunctions._faceRecog.FaceEncodings(image1, (IEnumerable<Location>)new Location[1]
                                    {
                        faceLocation
                                    }, 0).ToArray<FaceEncoding>();
                                    //if (array1 != null)
                                    {
                                        foreach (KeyValuePair<string, FaceEncoding> keyValuePair in ((IEnumerable<KeyValuePair<string, FaceEncoding>>)array1).Where<KeyValuePair<string, FaceEncoding>>((Func<KeyValuePair<string, FaceEncoding>, bool>)(pair => pair.Value != null)))
                                        {
                                            double num = FaceRecognitionDotNet.FaceRecognition.FaceDistance(((IEnumerable<FaceEncoding>)array2).First<FaceEncoding>(), keyValuePair.Value);
                                            if (num < 0.4)
                                            {
                                                _negetiveSample = 0;
                                                string _lbl = keyValuePair.Key;
                                                _lbl = Regex.Replace(_lbl, @"[\d-]", string.Empty);
                                                if (_postiveSample <= 0)
                                                {
                                                    _positiveLabel = _lbl;
                                                    ++_postiveSample;
                                                }
                                                else
                                                {
                                                    if (_positiveLabel == _lbl)
                                                    {
                                                        logger.WriteLog("Positve sample"+ _postiveSample,"Info");
                                                        ++_postiveSample;
                                                    }
                                                    else
                                                    {
                                                        _postiveSample = 0;
                                                        logger.WriteLog("Positve sample 000000" + _postiveSample, "Info");
                                                        _positiveLabel = "";
                                                    }
                                                }

                                            }
                                            else
                                            {
                                                logger.WriteLog("negetive sample" + _negetiveSample, "Info");
                                                ++_negetiveSample;
                                            }
                                        }

                                        foreach (FaceEncoding faceEncoding in array2)
                                            faceEncoding.Dispose();
                                    }
                                }
                            }

                        }
                        _isFrameProcessing = !_isFrameProcessing;
                    }
                }`
So that if i get five positive samples i can invoke the recognition completed and if there is more than ten negetive samples i can invoke recognition failed . This code is not that kind of accurate. If you could suggest any modification, that will be great. I hope you can see that I am a beginner in this. Any suggestions are deeply appreciated. Thank you

**Comment by takuya-takeuchi** [comment]
````
Marshal.Copy(mat.DataPointer, bytes, 0, bytes.Length);
````

Mat is OpenCVSharp? If so, it could be not RGB but BGR.
So loaded FaceRecognitionDotNet Image and face encoding may decrease accuracy.

**Comment by code861** [comment]
here Mat is Emgu CV and yes it is BGR. So I need to convert it to RGB before loading FaceRecognitionDotNet Image

**Comment by takuya-takeuchi** [comment]
I'm very sorry to late replay.

Yes, you have to convert it from bgr to rgb.

**Comment by code861** [comment]
Yup, that worked perfectly. Any changes in the code to get more accuracy?

**Comment by takuya-takeuchi** [comment]
you can ignore small face image.
Small face image may be low quality.

And you can check face landmark.
It means we should use frontal face rather than side face.

**Comment by code861** [comment]
how to use face landmark.Can you suggest a demo code

**Comment by takuya-takeuchi** [comment]
you can call FaceLandmark method.
and it return locations of face parts.
You check each parts location and judge whether face is suitable for face matching.

**Comment by code861** [comment]
how its done?

**Comment by khinklenj** [comment]
Any update on this question

**Comment by takuya-takeuchi** [comment]
@code861  @khinklenj 

Sorry delay response.

This code check whether face is front or side.
But it depends on threshold parameter.
I think you should not use in product.

````
using System;
using System.Linq;
using FaceRecognitionDotNet;

namespace Issue56
{

    internal class Program
    {

        private static void Main(string[] args)
        {
            var model = args[0];
            var image = args[1];
            
            var fr = FaceRecognition.Create(model);
            using(var img = FaceRecognition.LoadImageFile(image))
            {
				var face = fr.FaceLocations(img).FirstOrDefault();
                if (face == null)
                {
					Console.WriteLine($"face is not found from {image}");
                    return;
                }

                var landmark = fr.FaceLandmark(img, new [] {face}, PredictorModel.Large).FirstOrDefault();
                if (landmark == null)
                {
					Console.WriteLine($"face landmark is not founed from {image}");
                    return;
                }
                
				var left = landmark[FacePart.LeftEye];
				var right = landmark[FacePart.RightEye];

                var leftWidth = left.Max(p => p.X) - left.Min(p => p.X);
                var rightWidth = right.Max(p => p.X) - right.Min(p => p.X);

                Console.WriteLine($" leftWidth: {leftWidth}");
                Console.WriteLine($"rightWidth: {rightWidth}");

                const float threshold = 0.6f;
                var ratio = leftWidth < rightWidth ? leftWidth / (float)rightWidth : rightWidth / (float)leftWidth;
                if (ratio < threshold)
                    Console.WriteLine($"face is side. ratio is {ratio}");
                else
                    Console.WriteLine($"face is front. ratio is {ratio}");
			}
        }

    }

}
````

![front](https://user-images.githubusercontent.com/6241854/77223882-d96f1b00-6ba3-11ea-955f-c5a817215e32.jpg)

````
$ dotnet run -c Release -- models front.jpg
 leftWidth: 44
rightWidth: 51
face is front. ratio is 0.8627451
````

![side](https://user-images.githubusercontent.com/6241854/77223883-daa04800-6ba3-11ea-9661-46535078273f.jpg)

````
$ dotnet run -c Release -- models side.jpg
 leftWidth: 16
rightWidth: 30
face is side. ratio is 0.5333334
````

**Comment by takuya-takeuchi** [comment]
No Response
