### ISSUE TITLE
Write FaceEncodings element in MS SQL

### ISSUE THREAD

**Issue by NickPlehanov** [takuya-takeuchi/FaceRecognitionDotNet#58]
# Summary of your issue

# Environment

Write your environment.

# What did you do when you faced the problem?

Hi. I need to write in database(MS SQL) element, for next to use get picture an webcam

## Example code:

```
FaceRecognitionDotNet.Image image1 = FaceRecognition.LoadImageFile(@"C:\test\test.bmp");
            try {
                encoding1 = fr.FaceEncodings(image1, null, 1).First();
            }
            catch { encoding1 = null; }
            diff =  FaceRecognition.FaceDistance(encoding1,Clients_Image.lst_clnt_img[i].faceEncoding);
```

## Output:

```
paste your output
```

**Comment by takuya-takeuchi** [comment]
you can serialize FaceEncoding object and save it to where you want to.

**Comment by pierresa** [comment]
Sorry, but how do I serialize FaceEncoding, if I try I get the following error
InvalidOperationException: FaceRecognitionDotNet.FaceEncoding cannot be serialized because it does not have a parameterless constructor.

**Comment by takuya-takeuchi** [comment]
@pierresa 
No. FaceEncoding has Serializable attribution.
You can refer this test code.

https://github.com/takuya-takeuchi/FaceRecognitionDotNet/blob/523039304ba29f2c2dde111c9ec94aae1e47edae/test/FaceRecognitionDotNet.Tests/FaceRecognitionTest.cs#L390

**Comment by takuya-takeuchi** [comment]
No Response
