### ISSUE TITLE
What is different betwen Release and MinSizeRelease???

### ISSUE THREAD

**Issue by chenguangbankai** [takuya-takeuchi/FaceRecognitionDotNet#59]
Is Release better than MinSize ??? Thanks
(ps : When i builds dll for Native and Native.Dnn)

**Comment by takuya-takeuchi** [comment]
I guess it depends on compiler.
Basically, MinSize focus  on reducing binary size. It may decrease performance.
You should check compiler option!!

**Comment by chenguangbankai** [comment]
thanks
