### ISSUE TITLE
Get face encodings

### ISSUE THREAD

**Issue by eloelo22** [takuya-takeuchi/FaceRecognitionDotNet#6]
Hello,  i am trying to get the face encoding with this codes
` var bidenFile = "480px-Biden_2013.jpg";
 var path1 = Path.Combine(Directory.GetCurrentDirectory(), bidenFile);
 var image = FaceRecognition.LoadImageFile(path1);
  FaceEncoding[] encodings = _FaceRecognition.FaceEncodings(image).ToArray();`
what i am trying to do here is to get the actual array of the face encoding but on the foreach loop
`foreach (var enc in encodings)
            {
                Console.WriteLine(enc);
            }`
it displays this FaceRecognitionDotNet.FaceEncoding i am looking to get the actual face encoding such as `{ -0.33578}` and so on and i will actually save it on my sql lite as a form of enrollment for facial recognition and pull the encodings when its time to perform facial recognition

can you guide me on how to get the necessary value thank you

**Comment by eloelo22** [comment]
Daunting task for a programmer who aint to deep on c# but nevertheless i will try your suggestions and thank you great project

**Comment by eloelo22** [comment]
I will try thank you

**Comment by eloelo22** [comment]
ok i will try thank you

**Comment by takuya-takeuchi** [comment]
You must deploy DlibDotNet.Native.dll to execution directory.
This library is downloaded in packages directiry if you use nuget.

Last night, I added serialize function to FaceEncoding class. So it will be published to soon.

**Comment by takuya-takeuchi** [comment]
Ah, did you build DlibDotNet at FaceRecignitionl.sln?
If so, you must build DlibDotNet.Native and DlibDotNet.Dnn manually by cmake.

**Comment by eloelo22** [comment]
Cool i guess i just have to wait for the update

**Comment by takuya-takeuchi** [comment]
I released latest version which support serialize/deserialize for FaceEncoding class.

https://www.nuget.org/packages/FaceRecognitionDotNet/1.2.3.1
https://www.nuget.org/packages/FaceRecognitionDotNet-WithCUDA/1.2.3.1

Sampe code is below

````
[TestMethod]
public void SerializeDeserializeBinaryFormatter()
{
    const string testName = nameof(this.SerializeDeserializeBinaryFormatter);
    var directory = Path.Combine(ResultDirectory, testName);
    Directory.CreateDirectory(directory);

    var path = Path.Combine(ImageDirectory, TwoPersonFile);
    if (!File.Exists(path))
    {
        var binary = new HttpClient().GetByteArrayAsync($"{TwoPersonUrl}/{TwoPersonFile}").Result;

        Directory.CreateDirectory(ImageDirectory);
        File.WriteAllBytes(path, binary);
    }

    using (var image = FaceRecognition.LoadImageFile(path))
    {
        var encodings = this._FaceRecognition.FaceEncodings(image).ToArray();
        Assert.IsTrue(encodings.Length > 1, "");

        var dest = $"{path}.dat";
        if (File.Exists(dest))
            File.Delete(dest);

        var bf = new BinaryFormatter();
        using (var fs = new FileStream(dest, FileMode.OpenOrCreate))
            bf.Serialize(fs, encodings.First());

        using (var fs = new FileStream(dest, FileMode.OpenOrCreate))
        {
            var encoding = (FaceEncoding)bf.Deserialize(fs);
            var distance = FaceRecognition.FaceDistance(encodings.First(), encoding);
            Assert.IsTrue(Math.Abs(distance) < double.Epsilon);
        }

        foreach (var encoding in encodings)
            encoding.Dispose();

        foreach (var encoding in encodings)
            Assert.IsTrue(encoding.IsDisposed, $"{typeof(FaceEncoding)} should be already disposed.");
    }
}
````

**Comment by takuya-takeuchi** [comment]
Sorry, please use 1.2.3.2.

https://www.nuget.org/packages/FaceRecognitionDotNet/1.2.3.2
https://www.nuget.org/packages/FaceRecognitionDotNet-WithCUDA/1.2.3.2

**Comment by eloelo22** [comment]
first of all thank you for accommodating my request i tested the serialization and it worked but when getting the distance it is way off i used the same photo for serialization and compare face "480px-Biden_2013.jpg" on the compareface it returned false and the distance is way off 1.40253678451802 while i was using the same photo

**Comment by takuya-takeuchi** [comment]
thank you for your reporting.
oh, my unit test code may have something wrong.

now, i work in office. so plz wait until night.

**Comment by takuya-takeuchi** [comment]
I uploaded wrong DlibDotNet package.
19.15.0.20180911 contains old DlibDotNet.dll. Please update DlibDotNet to 19.15.0.20180913.
But if you use old one's, app should crash. Do you face crash issue?

And I tested your reported source code and I could not reproduce.

Could you test the following binary and code?

* [ConsoleApp1.zip](https://github.com/takuya-takeuchi/FaceRecognitionDotNet/files/2379322/ConsoleApp1.zip)
  * It is similar program with your code
* [Release.zip](https://github.com/takuya-takeuchi/FaceRecognitionDotNet/files/2379319/Release.zip)
  * It is binary of the above. Please deploy models directory and 480px-Biden_2013.jpg.

**Comment by takuya-takeuchi** [comment]
![image](https://user-images.githubusercontent.com/6241854/45489112-5eeb6100-b79e-11e8-9d3d-5e387c47f09a.png)

**Comment by eloelo22** [comment]
Nope no crashes at all. I will try and test it tomorrow tnx

**Comment by eloelo22** [comment]
How come you could use it on a full dot net framework?

**Comment by takuya-takeuchi** [comment]
What does it mean?
This sample uses .NET 4.7.1.

**Comment by yuzifu** [comment]
aceRecognitionDotNet can work on  .net 4.7

**Comment by takuya-takeuchi** [comment]
FaceRecognitionDotNet and DlibDotNet are built as .NET Standard 2.0 project.
It is supported by .NET Framework 4.6.1, .NET Core 2.0 and more.
It means that legacy framework can not use it.

Please refer the following document.
https://github.com/dotnet/standard/blob/master/docs/versions.md

**Comment by eloelo22** [comment]
![capture1](https://user-images.githubusercontent.com/8648535/45521856-8a983680-b7f2-11e8-9cff-93f3ee13efe3.PNG)
here is the result it's still way off on .net core but using your app it says true and distance is 0 should i just use .net framework rather than dot net core?
here is your's
![capture](https://user-images.githubusercontent.com/8648535/45522072-7dc81280-b7f3-11e8-8aa1-9dedbefa1b55.PNG)
