### ISSUE TITLE
How to use Bitmap type Facedetection?

### ISSUE THREAD

**Issue by flsl** [takuya-takeuchi/FaceRecognitionDotNet#62]
I saw Example
if filepath given,We can use code like:
FaceRecognitionDotNet.Image image = FaceRecognition.LoadImageFile();
if OpencvSharp given,We can use code like:
FaceRecognitionDotNet.Image image = FaceRecognition.LoadImage(byte[] arr,int rows,int cols,int elementsize);
But Bitmap given?I don not know how to write code.
I Use AForge.video Get Bitmap type Image.So How to facedetect?
what is the meaning about elementsize?

**Comment by takuya-takeuchi** [comment]
This could help you.
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/36#issuecomment-478267070

**Comment by futureflsl** [comment]
thanks
