### ISSUE TITLE
when FaceRecognition.Create(directory)  System.Runtime.InteropServices.SEHException

### ISSUE THREAD

**Issue by flsl** [takuya-takeuchi/FaceRecognitionDotNet#63]
I got source code example ,FaceDetection,But it cannot work,here is the code
 var directory = Path.GetFullPath("models");
                if (!Directory.Exists(directory))
                {
                    Console.WriteLine($"Please check whether model directory '{directory}' exists");
                    return;
                }
                if (_FaceRecognition == null)
                    _FaceRecognition = FaceRecognition.Create(directory);
I make sure that  models directory is right.in models,there are four files

dlib_face_recognition_resnet_model_v1.dat
mmod_human_face_detector.dat
shape_predictor_5_face_landmarks.dat
shape_predictor_68_face_landmarks.dat

However System.Runtime.InteropServices.SEHException  occured. I run it with VS2019

**Comment by takuya-takeuchi** [comment]
Could you confirm the path of models?
It may occur problem if the path contains non-alphanumeric char.

It may help to resolve issue.
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/21

**Comment by flsl** [comment]
thanks, path contains chinese,I change english,then it work!
