### ISSUE TITLE
Beginner friendly documentation.

### ISSUE THREAD

**Issue by petvas** [takuya-takeuchi/FaceRecognitionDotNet#64]
Please provide a step by step guide how to use the examples.
Like where to get the `shape_predictor_68_face_landmarks.dat` files etc..
How to deal with
Unable to load DLL `DlibDotNet.Native.dll` error....
I spent 3 hours to make it work but I can't, browsing the source give me some hint where I should put the Helen files from the page, but currently it is really hard get into this project.

**Comment by takuya-takeuchi** [comment]
How is this?
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/wiki/Quickstart

**Comment by petvas** [comment]
Great! Thank you!
