### ISSUE TITLE
How to specify helen shape predictor? 

### ISSUE THREAD

**Issue by Hershef** [takuya-takeuchi/FaceRecognitionDotNet#66]
How to specify helen shape predictor (implying i have helen-dataset.dat) when using FaceEncodings?

Currently it's hard coded to use predictor small, https://github.com/takuya-takeuchi/FaceRecognitionDotNet/blob/23c8d57c61fc74749fec1e6509f44f3af48d9a5b/src/FaceRecognitionDotNet/FaceRecognition.cs#L262

**Comment by takuya-takeuchi** [comment]
@Hershef 
No. You should use `FaceLandmark` method rather than `RawFaceLandmarks`

**Comment by takuya-takeuchi** [comment]
No Response
