### ISSUE TITLE
There was an error running the project on Centos

### ISSUE THREAD

**Issue by lcc777** [takuya-takeuchi/FaceRecognitionDotNet#67]
I used nuget in the project to reference FaceRecognitionDotNet, which works fine on the windows platform, but there is an error in copying files to Centos after publishing.
The error is as follows:
System.DllNotFoundException: Unable to load shared library 'DlibDotNetNative' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libDlibDotNetNative: cannot open shared object file: No such file or directory
It seems to be because of the dependency problem, but I have no idea, I hope to get your help, thank you.
System: Centos7
Sdk: .net core 2.1

**Comment by Novice-Liuer** [comment]
It is an error caused by DlibDotNet.NativeMethods.get_frontal_face_detector()

**Comment by takuya-takeuchi** [comment]
In docker container,

````
# ldd /opt/FaceRecognitionDotNet/05.#67/bin/x64/Release/netcoreapp2.0/libDlibDotNetNative.so
/opt/FaceRecognitionDotNet/05.#67/bin/x64/Release/netcoreapp2.0/libDlibDotNetNative.so: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /opt/FaceRecognitionDotNet/05.#67/bin/x64/Release/netcoreapp2.0/libDlibDotNetNative.so)
/opt/FaceRecognitionDotNet/05.#67/bin/x64/Release/netcoreapp2.0/libDlibDotNetNative.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /opt/FaceRecognitionDotNet/05.#67/bin/x64/Release/netcoreapp2.0/libDlibDotNetNative.so)
/opt/FaceRecognitionDotNet/05.#67/bin/x64/Release/netcoreapp2.0/libDlibDotNetNative.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /opt/FaceRecognitionDotNet/05.#67/bin/x64/Release/netcoreapp2.0/libDlibDotNetNative.so)
        linux-vdso.so.1 =>  (0x00007ffc300ee000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f39cfd61000)
        libX11.so.6 => not found
        libopenblas.so.0 => not found
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f39cfa5a000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f39cf758000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f39cf542000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f39cf175000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f39d1e04000)
````

You must install openblas and X11.

**Comment by Novice-Liuer** [comment]
I installed libopenblas according to your ideas, unfortunately it still has the same error.
```
ldd libDlibDotNetNative.so 
./libDlibDotNetNative.so: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./libDlibDotNetNative.so)
./libDlibDotNetNative.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./libDlibDotNetNative.so)
./libDlibDotNetNative.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./libDlibDotNetNative.so)
	linux-vdso.so.1 =>  (0x00007fff269b5000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f05d3c0c000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f05d38ce000)
	libopenblas.so.0 => /home/huhangmed/t/OpenBLAS/libopenblas.so.0 (0x00007f05d32e6000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f05d2fdf000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f05d2cdd000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f05d2ac7000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f05d26f9000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f05d5caf000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f05d24d1000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f05d22cd000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f05d20c9000)
```

**Comment by takuya-takeuchi** [comment]
@Novice-Liuer 
CentOS7 has old gcc and g++.
So you have to update them.

This link may help you.
https://medium.com/@t1neo/2-ways-of-usr-lib64-libstdc-so-5-version-cxxabi-1-3-8-glibcxx-3-4-20-not-found-decd76c10db1

**Comment by Hershef** [comment]
Had the same error on centos 7 / ubuntu 16 but not on debian 9, using ldd on libDlibDotNetNative.so to find what is missing or needs to be upgraded helped me on Ubuntu 16, it's quite easy but tricky to find the right packages, in my case openblas needed to be installed and glibcxx too (to the right version)

**Comment by takuya-takeuchi** [comment]
@Hershef 
I provide dockerfile for ubuntu16.

## Base
https://github.com/takuya-takeuchi/DlibDotNet/blob/master/docker/base/ubuntu/16/cpu/x64/Dockerfile

## Runtime (derive from Base)
https://github.com/takuya-takeuchi/DlibDotNet/blob/master/docker/runtime/ubuntu/16/Dockerfile

I think it does not need any tricky tech to find right package.

**Comment by Hershef** [comment]
I agree, it was easy on ubuntu 16, i use it too. CentOs7 went problematic with multiple repos and how it handles alternative packages though

**Comment by takuya-takeuchi** [comment]
@Novice-Liuer
I tried to build dlib on centos7 container. It seems there is no problem.
This container installed x11, openblas and lapack but not installed latest gcc.
It means that it could not show error "`CXXABI_1.3.8' not found".

Now, I will check whether dlibdotnet sample program works or not.

**Comment by takuya-takeuchi** [comment]
DONE.
https://github.com/takuya-takeuchi/DlibDotNet/commit/82729b2fb35900cd97a6dfa3589ee6c6a5ca2657

DlibDotNet CUDA, MKL and CPU works on centos container.

**Comment by takuya-takeuchi** [comment]
Next version includes CentOS's binary.

**Comment by takuya-takeuchi** [comment]
And I should update wiki to explain how to install dependencies (X11 and openblas).
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/69

**Comment by Novice-Liuer** [comment]
Thank you very much for your help, I have successfully run my app on Ubuntu.
Best regards

**Comment by huanbd** [comment]
Hi @takuya-takeuchi, I've deployed code to Centos 7 but I still have error although I've followed guide in wiki
```
sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
sudo yum install libX11-devel openblas-devel
```
`ldd: ./libDlibDotNetNative.so: No such file or directory`
Can I miss something?

**Comment by huanbd** [comment]
Hi, For anyone who has encountered the same error as me. 
I've added nuget DlibDotNet in my project, and build again with Platform x64 (before I've builded Any-CPU :) ). So It run!.

**Comment by takuya-takeuchi** [comment]
It seems the reporter can resolve issue.
