### ISSUE TITLE
FaceEncodings forced to use 5 point predictor instead of 68

### ISSUE THREAD

**Issue by Hershef** [takuya-takeuchi/FaceRecognitionDotNet#71]
Can we add an option to specify predictor model to FaceEncodings? instead of forcing it to small (5 points) so we can use 68 points (large) like the python package

(I already edited the source / re compiled for own purpose, this issue is for other people)
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/blob/23c8d57c61fc74749fec1e6509f44f3af48d9a5b/src/FaceRecognitionDotNet/FaceRecognition.cs#L262

**Comment by takuya-takeuchi** [comment]
@Hershef 
Thank you for your suggestion.
OK. Does it satisfy your requiments?

````
public IEnumerable<FaceEncoding> FaceEncodings(Image image, IEnumerable<Location> knownFaceLocation = null, int numJitters = 1, PredictorModel model = PredictorModel.Small)
        {
            if (image == null)
                throw new ArgumentNullException(nameof(image));

            image.ThrowIfDisposed();
            this.ThrowIfDisposed();

            var rawLandmarks = this.RawFaceLandmarks(image, knownFaceLocation, model);
            foreach (var landmark in rawLandmarks)
            {
                var ret = new FaceEncoding(FaceRecognitionModelV1.ComputeFaceDescriptor(this._FaceEncoder, image, landmark, numJitters));
                landmark.Dispose();
                yield return ret;
            }
        }
````

**Comment by takuya-takeuchi** [comment]
Added new argument for FaceEncodings method on develop branch
1a979d2ae852c89aab245a2da478c2d790faf38f

**Comment by takuya-takeuchi** [comment]
## Note 

This request was already introcued in https://github.com/ageitgey/face_recognition/commit/4d7bc049468ee78c971c2609af8979f1ab092584

close.
