### ISSUE TITLE
Any simple method to support 32bit os?

### ISSUE THREAD

**Issue by MiyamuraMiyako** [takuya-takeuchi/FaceRecognitionDotNet#72]
In some scenes, such as Kiosk devices run 32bit windows7 os.

**Comment by takuya-takeuchi** [comment]
latest dlibdotnet 19.18.0.20190928 supportx x86, so you could use it instead of what frdn depends on.
however, frdn and dlibdotnet requires huge memory to detect faces.
x86 machine may get to be hang up.

**Comment by MiyamuraMiyako** [comment]
Thank you, Problem solved.
