### ISSUE TITLE
Training Helen

### ISSUE THREAD

**Issue by tgd-git** [takuya-takeuchi/FaceRecognitionDotNet#75]
For landmark generation you note:

> The above landmark is generated by Helen dataset. Please check http://www.ifp.illinois.edu/~vuongle2/helen/ and create model file by examples/HelenTraining. I will NOT provide pretrained model file.

How do you do this? Is there any documentation on the process. I dont understand the commandline options. Should i train, should i generate? What does demo mean? Not familiar with this at all and the command help does not help me. 

1. Have downloaded shape_predictor_68_face_landmarks.dat and put into models subdir. 
2. Have downloaded the helen zips. Not sure where to put them.
2. Have build solution and start HelenTraining.dll from the debug dir as follows:

> dotnet HelenTraining.dll generate -m C:\FaceSketcher\FaceRecognitionDotNet\examples\HelenTraining\bin\Debug\netcoreapp2.0\models -p 0

Getting errors about DlibDotNetNative

```
C:\FaceSketcher\FaceRecognitionDotNet\examples\HelenTraining\bin\Release\netcoreapp2.0>dotnet HelenTraining.dll generate -m C:\FaceSketcher\FaceRecognitionDotNet\examples\HelenTraining\bin\Debug\netcoreapp2.0\models -p 0
Model: C:\FaceSketcher\FaceRecognitionDotNet\examples\HelenTraining\bin\Debug\netcoreapp2.0\models
Padding: 0

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'DlibDotNetNative' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at DlibDotNet.NativeMethods.get_frontal_face_detector()
   at FaceRecognitionDotNet.FaceRecognition..ctor(String directory) in C:\FaceSketcher\FaceRecognitionDotNet\src\FaceRecognitionDotNet\FaceRecognition.cs:line 66
   at HelenTraining.Program.<>c__DisplayClass1_1.<Main>b__3() in C:\FaceSketcher\FaceRecognitionDotNet\examples\HelenTraining\Program.cs:line 75
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at HelenTraining.Program.Main(String[] args) in C:\FaceSketcher\FaceRecognitionDotNet\examples\HelenTraining\Program.cs:line 350
```
 The Build dir:
![image](https://user-images.githubusercontent.com/2562637/74265616-276e4480-4d03-11ea-8222-b15acfc96a81.png)

**Comment by takuya-takeuchi** [comment]
The program of examples directory does not use nuget package.
Therefore you must copy DlibDotNetNative.dll and DlibDotNetDnnNativeDnn.dll to output directory.
You can obtain them from DlibDotNet Nuget package or local Nuget cache.

**Comment by tgd-git** [comment]
ok i see, got the dlls and the error is gone, thanks! still not sure how to proceed with the training.
can you please outline the steps?

When i run the command below nothing really happens. 
```
dotnet HelenTraining.dll generate -m C:\FaceSketcher\FaceRecognitionDotNet\examples\HelenTraining\bin\Debug\netcoreapp2.0\models -p 0
```
The output is just like this. No confirm, no error, just getting back to prompt:
```
Model: C:\FaceSketcher\FaceRecognitionDotNet\examples\HelenTraining\bin\Debug\netcoreapp2.0\models
Padding: 0
```

I have put helen_1-5.zip and annotation.zip right beside HelenTraining.dll in the same folder

**Comment by takuya-takeuchi** [comment]
OK. I found error reason. This is code issue.
DlibDotNet which in src directory is too latest.

So

1. Download DlibDotNet 19.17.0.20190623 and extract DlibDotNetNative and DlibDotNetNativeDnn
  - Sure, You can use DlibDotNet.CUDA100, DlibDotNet.CUDA101, DlibDotNet.CUDA92
2. Go to src/DlibDotNet and execute`git checkout b78c05f`
3. Build and run HelenTraining

It should start generate xml file.

**Comment by tgd-git** [comment]
Followed the steps but stuck again with "Unable to load DLL 'DlibDotNetNative' " error.

1. Downloaded DlibDotNet 19.17.0.20190623 nuget. Unzipped and located both dlls in `dlibdotnet.cuda101.19.17.0.20190623\runtimes\win-x64\native`. (DlibDotNetNativeDnn.dll and DlibDotNetNative.dll ver 19.17.0.20190623) Moved them into the build dir `..\FaceRecognitionDotNet\examples\HelenTraining\bin\Debug\netcoreapp2.0\`

2. Been to` ..\FaceRecognitionDotNet\src\DlibDotNet` and checked out b78c05f from 22.6.19

3. Rebuilt solution

Tried to build for x64 but no luck, same error.

Error:
```
C:\_SELFIES\FaceRecognitionDotNet\examples\HelenTraining\bin\Debug\netcoreapp2.0>dotnet HelenTraining.dll generate -m C:\_SELFIES\FaceRecognitionDotNet\examples\HelenTraining\bin\Debug\netcoreapp2.0\models -p 0
Model: C:\_SELFIES\FaceRecognitionDotNet\examples\HelenTraining\bin\Debug\netcoreapp2.0\models
Padding: 0

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'DlibDotNetNativeDnn' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at DlibDotNet.NativeMethods.loss_mmod_deserialize(Byte[] fileName, Int32 type, IntPtr& net, IntPtr& errorMessage)
   at DlibDotNet.Dnn.LossMmod.Deserialize(String path, Int32 networkType) in C:\_SELFIES\FaceRecognitionDotNet\src\DlibDotNet\src\DlibDotNet\Dnn\LossMmod.cs:line 107
   at FaceRecognitionDotNet.FaceRecognition..ctor(String directory) in C:\_SELFIES\FaceRecognitionDotNet\src\FaceRecognitionDotNet\FaceRecognition.cs:line 75
   at FaceRecognitionDotNet.FaceRecognition.Create(String directory) in C:\_SELFIES\FaceRecognitionDotNet\src\FaceRecognitionDotNet\FaceRecognition.cs:line 188
   at HelenTraining.Program.<>c__DisplayClass1_1.<Main>b__3() in C:\_SELFIES\FaceRecognitionDotNet\examples\HelenTraining\Program.cs:line 75
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at HelenTraining.Program.Main(String[] args) in C:\_SELFIES\FaceRecognitionDotNet\examples\HelenTraining\Program.cs:line 349

C:\_SELFIES\FaceRecognitionDotNet\examples\HelenTraining\bin\Debug\netcoreapp2.0>
```

**Comment by takuya-takeuchi** [comment]
`Unable to load DLL` mean that there is no some dependency library of DlibDotNetNativeDnn.
But DlibDotNetNativeDnn depends on MSVC runtime.
Do you install MSVC runtime?

**Comment by tgd-git** [comment]
Yes have plenty of them:
![image](https://user-images.githubusercontent.com/2562637/74349321-601a2680-4db4-11ea-9534-6fedc8f40d06.png)
Also cuda stuff:
![image](https://user-images.githubusercontent.com/2562637/74349416-850e9980-4db4-11ea-9bc7-53ac5f4bb0ac.png)

Anything else i can check?

**Comment by takuya-takeuchi** [comment]
> dlibdotnet.cuda101.19.17.0.20190623
Oh, you used cuda package?
You must deploy cudnn to CUDA install directory.

For example, `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\cudnn64_7.dll`

**Comment by tgd-git** [comment]
Ok i had no luck deploying cudnn like you suggested above. But have now downloaded the DlibDotNet 19.17.0.20190623 nuget without cuda and grabbed the dlls from there. Now helen training has started! Thanks for the support.
