### ISSUE TITLE
FaceRecognition from folder

### ISSUE THREAD

**Issue by khinklenj** [takuya-takeuchi/FaceRecognitionDotNet#78]
Hi, 
I have been trying to figure out how I can get an image from the web cam and compare that to a folder with different faces in it and validate that the face from the web cam is in that folder of faces.

I have figured out how to get the web cam image using OpenCVSharp.

But can not figure out how to verify the web cam face is in a source folder

Thank you
Keith

**Comment by takuya-takeuchi** [comment]
you can check https://github.com/takuya-takeuchi/FaceRecognitionDotNet/wiki/Quickstart#usage
you can load image from directoryl

**Comment by khinklenj** [comment]
How can I improve the speed. 

I merge all the photos in the folder into one image

If there is one file the system takes 1.3 seconds but if i run 3 or more images it takes 3+ seconds

Do you have any suggestions?

using (Image imageB = FaceRecognition.LoadImageFile(@"C:\temp\Merge.jpg"))
            {
                FaceEncoding[] encodingA = fr.FaceEncodings(WebCapture).ToArray();
                if (encodingA.Length == 0)
                {
                    isMatching = false;
                    goto updateui;
                }

                FaceEncoding[] encodingB = fr.FaceEncodings(imageB).ToArray();

                const double tolerance = 0.6d;
                bool match = FaceRecognition.CompareFace(encodingA.First(), encodingB.First(), tolerance);
                if (MatchFound == false)
                    MatchFound = match;
            }
        updateui:
            DateTime endtime = System.DateTime.Now;
            var diffInSeconds = (endtime - starttime).TotalSeconds;
            this.label1.BeginInvoke((MethodInvoker)delegate () { this.label1.Text = "Match Found: " + MatchFound.ToString() + " in " + diffInSeconds; });

**Comment by takuya-takeuchi** [comment]
@khinklenj 
Do you always create encode data from existing image when new image comes?
You can serialize face encoding data and you can skip findlocation and faceencoding process.

https://github.com/takuya-takeuchi/FaceRecognitionDotNet/blob/1d99e43591f6996910ab1a2abc0facbdd1ee24f4/src/FaceRecognitionDotNet/FaceRecognition.cs#L254

FaceEncoding method calls FaceLocation process if knownFaceLocation is null.

**Comment by takuya-takeuchi** [comment]
@khinklenj 
Do you always create encode data from existing image when new image comes?
You can serialize face encoding data and you can skip findlocation and faceencoding process.

https://github.com/takuya-takeuchi/FaceRecognitionDotNet/blob/1d99e43591f6996910ab1a2abc0facbdd1ee24f4/src/FaceRecognitionDotNet/FaceRecognition.cs#L254

FaceEncoding method calls FaceLocation process if knownFaceLocation is null.

**Comment by takuya-takeuchi** [comment]
no response
