### ISSUE TITLE
Detect if a person blinks 3 times

### ISSUE THREAD

**Issue by khinklenj** [takuya-takeuchi/FaceRecognitionDotNet#79]
With your Facial Recognition I want to stop a user from putting a picture of my face in front of the web cam and it matching my face.

Do you have a way in your code to detect if the user blinks 3 times this way I can determine if it is a real person and not a picture

thank you

**Comment by takuya-takeuchi** [comment]
FaceRecognition has facelandmark method and you can get eye points vector.
It would help you.
https://www.pyimagesearch.com/2017/04/24/eye-blink-detection-opencv-python-dlib/

**Comment by takuya-takeuchi** [comment]
no response
