### ISSUE TITLE
Can't find DlibDotNetNative.dll and DlibDotNetDnn.dll files. 

### ISSUE THREAD

**Issue by SamuelvVelzen** [takuya-takeuchi/FaceRecognitionDotNet#80]
Hi, 
First of all great wrapper, it seems like it is a very powerful library. 

However when I try to train Helen I can't find the DlibDotNetNative.dll and DlibDotNetDnn.dll files. 

I followed the instructions:
- download models
- entered "dotnet build -c Release"

I was wondering I someone could help me locate them. Thanks!

**Comment by takuya-takeuchi** [comment]
@SamuelvVelzen 

DlibDotNetNative and DlibDotNetNativeDnn dll is not included in repository.
You can build it from DlibDotNet project or download DlibDotNet nuget packge and extract it.

And I'm very sorry to trouble you.
Current DlibDotNet project in solution has gap for FaceRecognitonDotNet.

Next release, update dlibdotnet and some issue, helen training program.

Please refer this issue about the above information,
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/77

**Comment by SamuelvVelzen** [comment]
Hi Takuya,

Thanks for reacting so fast and trying to help everybody. 
After your answers I still have some questions. I was wondering if you could be bother to answer them.

First of all I want to include that I am trying this from a Mac using .NET Core 3.1.101. I am telling you this because I was wondering if this is supported because after read your dependencies libraries and products I came across OpenCVSharp that only supports windows and ubuntu. And I thought that dependencies had to be included in the project. Also when I downloaded your DlibDotNet project and when I tried to run it it gave the error that it didn't find assemblies for .NETFramework, version 4.6.1. 

**example error:**
`/usr/local/share/dotnet/sdk/3.1.101/Microsoft.Common.CurrentVersion.targets(1175,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.6.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/Users/Samuel/Downloads/DlibDotNet-master/examples/WPF/FaceLandmarkDetection/FaceLandmarkDetection.csproj]`

I was wondering if you could explain more about how I could extract the files from a nugget package. Because when I try to add a nugget package it can't find a project. 

As last question I was wondering you meant with you comment about the current DlibDontNet project. Could you explain this a bit more: 
`Current DlibDotNet project in solution has gap for FaceRecognitonDotNet.`

I am looking forward for your next release!

**Comment by takuya-takeuchi** [comment]
@SamuelvVelzen 

I assume there is 3 questions.

> Also when I downloaded your DlibDotNet project and when I tried to run it it gave the error that it didn't find assemblies for .NETFramework, version 4.6.1.

This program is not targeted to be working on not windows.
Because target framework is .NET Framework rather than .NET Core.

> I was wondering if you could explain more about how I could extract the files from a nugget package. Because when I try to add a nugget package it can't find a project.

There is 2 methods.

* change extension from *.nupkg to *.zip and extract it.
* access to **~/.nuget/packages/dlibdotnet/19.18.0.20200301/runtimes/osx-x64/native**
  * this has *.so. *.dylib or *.dll

> As last question I was wondering you meant with you comment about the current DlibDontNet project. Could you explain this a bit more

There is no deep reason.
The last release of FaceRecognitionDotNet is June 2019. On the other hand, the last release of DlibDotNet is Dec 2019.
Especially, DlibDotNet has minor bug and age/gender classification function depends on latest DlibDotNet.
So I must update it.

BTW, you can play HelenTraining by modify reference setting of DlibDotNet.
Current setting referes ../src/DlibDotNet and ../src/FaceRecognitionDotNet project.
But you can modify from it to nuget package. then build system will copy and reference proper binary automatically.

**Comment by SamuelvVelzen** [comment]
Thanks for your lengthy explanation, it helped me so much. I could find DlibDotNetNative.dll and DlibDotNet**Native**Dnn.dll files. However I couldn't find the DlibDotNetDnn.dll file and I was wondering if this was a type error?

Also when I try to train Helen I follow these steps:
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/tree/develop/examples/HelenTraining

However because I couldn't find the DlibDotNetDnn.dll file so I added the DlibDotNetNativeDnn.dll file. But when I try to generate the model using the following command:
`dotnet run -c Release -- generate -m "models" -p 50`

It throws this error: 
`
Model: models
Padding: 50

Unhandled Exception: System.TypeInitializationException: The type initializer for 'DlibDotNet.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'DlibDotNetNativeDnn': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at DlibDotNet.NativeMethods.LossMetric_anet_type_create()
   at DlibDotNet.NativeMethods..cctor() in /Users/Samuel/Downloads/FaceRecognitionDotNet-master/src/DlibDotNet/src/DlibDotNet/PInvoke/NativeMethods.cs:line 40
   --- End of inner exception stack trace ---
   at DlibDotNet.NativeMethods.get_frontal_face_detector()
   at FaceRecognitionDotNet.FaceRecognition..ctor(String directory) in /Users/Samuel/Downloads/FaceRecognitionDotNet-master/src/FaceRecognitionDotNet/FaceRecognition.cs:line 70
   at HelenTraining.Program.<>c__DisplayClass1_1.<Main>b__4() in /Users/Samuel/Downloads/FaceRecognitionDotNet-master/examples/HelenTraining/Program.cs:line 76
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at HelenTraining.Program.Main(String[] args) in /Users/Samuel/Downloads/FaceRecognitionDotNet-master/examples/HelenTraining/Program.cs:line 411
`

I was wondering if you knew what this error is and how to fix it.

**Comment by takuya-takeuchi** [comment]
you should copy libDlibDotNetNative.dylib and lib DlibDotNetNativeDnn.dyllub rather than *.dll for OSX.

**Comment by SamuelvVelzen** [comment]
Thank you, this fixed the problem I could build and train the dataset without almost any problem. 

I still have a few questions about the usability of the dataset but will open a new issue post about it so this question will remain clean.

**Comment by HEYRIX** [comment]
@SamuelvVelzen Hi Samuel, May I please ask you to help to fix some questions on this sample?
