### ISSUE TITLE
Side face detection

### ISSUE THREAD

**Issue by takuya-takeuchi** [takuya-takeuchi/FaceRecognitionDotNet#81]
Thanks @takuya-takeuchi I'll give it a shot. On a different topic, could you suggest a model or algorithm for side face detection? Thanks, always appreciate the feedback.

_Originally posted by @atabora1 in https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/36#issuecomment-592090795_

**Comment by takuya-takeuchi** [comment]
https://cvrl.nd.edu/projects/data/

und open ear dataset.
I don't check content but this paper uses it for side face.
https://www.researchgate.net/publication/220888669_Automatic_3D_Facial_Region_Retrieval_from_Multi-pose_Facial_Datasets#pf8

Therefore you can train it and generate orihinal dataset.

**Comment by atabora1** [comment]
Thank you

**Comment by takuya-takeuchi** [comment]
@atabora1 
I implemented sample code to detect side face or not.
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/56#issuecomment-602020550

It may be fuzy but not bad.

**Comment by takuya-takeuchi** [comment]
No Response
