### ISSUE TITLE
Helen Dataset, effectivity and other options

### ISSUE THREAD

**Issue by SamuelvVelzen** [takuya-takeuchi/FaceRecognitionDotNet#84]
Hi Takuya,

After training the Helen dataset I was wondering how good this dataset is and if it is possible to use other options if this one is not sufficient enough. Could I just specify a different model when calling the `ShapePredictor.Deserialize` function?

Also I was wondering how often I have to retrain this dataset. Does it get updates or is it a one time train dataset.

**Comment by takuya-takeuchi** [comment]
> After training the Helen dataset I was wondering how good this dataset is and if it is possible to use other options if this one is not sufficient enough. Could I just specify a different model when calling the ShapePredictor.Deserialize function?

No. The current implementation focus on becoming near face_recognition implementation. 
So user needs not to specify model file name.
But I consider next release 1.3.0 will adopt plugin system like the following.

````
class HelenDatasetFaceLandmark: FaceLandmarkBase
{
}

var detector1 = new HelenDatasetFaceLandmark("model1.dat");
var detector2 = new HelenDatasetFaceLandmark("model2.dat");
var fr = new FaceRecogniton("models");

fr.SetCustomFaceLandmarkDetector(detector1);
// PredictorModel.Helen will be abolished.
var landmarks1 = fr.FaceLandmark(image, null, PredictorModel.Custom);

fr.SetCustomFaceLandmarkDetector(detector2);
var landmarks2 = fr.FaceLandmark(image, null, PredictorModel.Custom);
````

HelenDatasetFaceLandmark will be default class.
Sure, the above may change or be not adopted.

> Also I was wondering how often I have to retrain this dataset. Does it get updates or is it a one time train dataset.

This issue/question must be treated as new issue.
TBH, I don't know what you say.
Could you explain more detail in #85?

**Comment by SamuelvVelzen** [comment]
The flexibility of that sounds great. So that means that in the future you could specify a different dataset, for example this one: 
https://arxiv.org/abs/1905.04830

**Comment by takuya-takeuchi** [comment]
It's very interesting paper.
Especailly, 3DDFA dataset has posibility to let us estiamte  3dFace pose.
Thanks.
