### ISSUE TITLE
Gender prediction example missing DLL

### ISSUE THREAD

**Issue by atabora1** [takuya-takeuchi/FaceRecognitionDotNet#86]
Hi @takuya-takeuchi 
I’m attempting to run the Gender Training example. When I build the project, I’m missing the files referenced. DlibDotNetNative.dll***, ***DlibDotNetNativeDnn.dll*** and ***DlibDotNetNativeDnnGenderClassification.dll* 
Any suggestions? 
The build works fine without errors. 
Thanks,

https://github.com/takuya-takeuchi/FaceRecognitionDotNet/tree/master/examples/GenderTraining

**Comment by takuya-takeuchi** [comment]
latest nuget package 1.2.3.14 contains these library. extract these from it.
Or you can build it from source code.

https://github.com/takuya-takeuchi/FaceRecognitionDotNet/tree/master/src/DlibDotNet.Native.Dnn.AgeClassification
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/tree/master/src/DlibDotNet.Native.Dnn.GenderClassification

**Comment by atabora1** [comment]
I was able to get DlibDotNetNative.dll and DlibDotNetNativeDnn.dll from nuget however DlibDotNetNativeDnnGenderClassification.dll wasn't present in nuget. I also attempted to build it following the instructions on this page however that was unsuccessful. Screenshot attached. 
![Dlib-build-warning](https://user-images.githubusercontent.com/33614374/76173323-bbdd9280-615b-11ea-8375-6f2eda7fe0c7.png)
![Dlib-build-warning-2](https://user-images.githubusercontent.com/33614374/76173324-bd0ebf80-615b-11ea-8aab-023fa24abfc3.png)

**Comment by takuya-takeuchi** [comment]
no. latest package is FaceRecognitionDotNet.

**Comment by takuya-takeuchi** [comment]
No Response

**Comment by FrankenApps** [comment]
I ran into the same problem, just wanted to point out, these are in your local .nuget directory normally `C:\User\Username\.nuget` and then in the path `\packages\facerecognitiondotnet\1.3.0.2\runtimes\win-x64\native`.
