### ISSUE TITLE
FaceRecognition.CompareFace

### ISSUE THREAD

**Issue by khinklenj** [takuya-takeuchi/FaceRecognitionDotNet#87]
During FaceRecognition.CompareFace how many points does it compare

How do I get the Accuracy number from FaceRecognition.CompareFace.

How can I improve FaceRecognition.CompareFace.

**Comment by takuya-takeuchi** [comment]
face encoding has 128 x 1  vector.
FaceRecignitionDotNet dies not take care of content of this vector.
because this comparison us executed in dlib.

and this comparison is very fast.
I think we need not to work on improvement.

**Comment by takuya-takeuchi** [comment]
No Response
