### ISSUE TITLE
Face Rec on side profile

### ISSUE THREAD

**Issue by khinklenj** [takuya-takeuchi/FaceRecognitionDotNet#90]
I am finding that if a user's head is turned to the side I can not get an accurate Face Rec compare

What steps would you recommend to improve this.

Should I take multiple images of the user's side profile form both sides and compare that to stored images i have of their side profiles

Also how can I get a percentage of how accurate the system feels that person is to an image.

Thank you
Keith

**Comment by takuya-takeuchi** [comment]
face_recognition could be focusing on front face. FaceRecognitionDotNet is also same.
In spite of same length 128, side face encoding has twice of density data compared to side part of front encoding.
So accuracy could be got down if comparing between front and side.

NOTE: face encoding data could not separate into face part. face encoding has not face part information.

So we should take both side and front face data.


Some of company (Amazon, NEC, Panasonic, Google and etc) face recognition systems may support comparing between front and side.

> Also how can I get a percentage of how accurate the system feels that person is to an image.

Does it mean face image quality and extracted feature/encoding quality?
No. face_recognition and FaceRecognitionDotNet do not have them.

**Comment by takuya-takeuchi** [comment]
FYI
https://arxiv.org/pdf/1904.01740.pdf

FaceQNet is from ResNet50.

**Comment by takuya-takeuchi** [comment]
No Response
