### ISSUE TITLE
How to get the best results

### ISSUE THREAD

**Issue by ehrsten** [takuya-takeuchi/FaceRecognitionDotNet#91]
Hi

Lets say i have 5 encodings of each person. Now when i do face recognition i check all the 5 encodings against the face encoding that was sent.

Is this the best way to get the end result:
![image](https://user-images.githubusercontent.com/62869426/77916550-e7a6f080-72a1-11ea-8caf-fa966ba90324.png)

I mean, i can also check if their all true or if 4/5 is true, but is this how i should approch the recognition phase?

**Comment by takuya-takeuchi** [comment]
@ehrsten 
Majority decision is not bad.
I guess there is low face quality image and it occurs increase distance between query and target.
So we should use majority decision if we can not take high quality image (front facial).
