### ISSUE TITLE
FaceRecognition.LoadImage usages

### ISSUE THREAD

**Issue by SamuelvVelzen** [takuya-takeuchi/FaceRecognitionDotNet#92]
Hi,
I have a byte array but I want to use LoadImage function. After checking documentation I saw you need 4 parameters; byte[] array, int row, int column and int elementsize. 

I was wondering is it possible to use byte array to get height and width? 

Also what is elementsize? I saw you could only input 1 or 3 but which one do I have to choose?

**Comment by takuya-takeuchi** [comment]
@SamuelvVelzen 

Sorry. I am very busy now. So I didn't yet answer your another question.

> Also what is elementsize?
The elementSize is used to determine whether byte array is rgb or grayscale image.
If byte array is rgb, byte array could be B, G, R, B, G, R......
It means that one pixel is RGB. In other words, one pixel is 3 element.
And api expect that height x widht * elemSize equal to array.Length.

>  I saw you could only input 1 or 3 but which one do I have to choose?
Yes, you can only choice 1 or 3. So this parameter could confuse developer. sorry.

**Comment by SamuelvVelzen** [comment]
No worries! I really appreciate the time you have already taken. Take your time and get back at me when you have some time. I hope you feel alright in these weird times 😀

**Comment by SamuelvVelzen** [comment]
I was wondering if you had the change to look it over and if you could answer me 😬

**Comment by takuya-takeuchi** [comment]
sorry. what do you want me to do? I'm bit confusing.
Please line up what you hope (e.g. add function or fix bug).

thanks.

**Comment by SamuelvVelzen** [comment]
sorry my bad, I read your response again and I saw you answered me already. I was confused 🙃

I do however have a question:
- I have a base64string 
- convert it to a byte[] using ```Convert.FromBase64String```
- I get the width and height using ```new Bitmap(new MemoryStream(byte[]))```
- throws error: ```System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'array.Length should equal to row x column x elementSize.')```

Do you know why this went wrong?

**Comment by takuya-takeuchi** [comment]
@SamuelvVelzen 
You could hit https://github.com/takuya-takeuchi/DlibDotNet/blob/4733dbf1eeab2b59a240fd48f88d840eaba47c16/src/DlibDotNet/Matrix/Matrix.cs#L297
Please check Bitmap.PixelFormats. It may be 32bit bitmap.
FaceRecognitionDotNet does not support 32bit image.
If bitmap is 24bit, you must specify 3 as elementSize.

Thanks.

**Comment by SamuelvVelzen** [comment]
I checked using 
```
using (var ms = new MemoryStream(byteArr))
Bitmap bmp = new Bitmap(ms);
Console.WriteLine(bmp.PixelFormat);
```
And it says it is a Format24bppRgb. So that is not the problem.

**Comment by takuya-takeuchi** [comment]
@SamuelvVelzen 
Ok, I have a time to work on your issue.
Could you update minimum source code and sample data?

**Comment by SamuelvVelzen** [comment]
yeah!

I have uploaded my minimum source code here:
https://github.com/SamuelvVelzen/loadimageissue

however you have to upload a Helen-dataset.dat file in the datasets folder because I couldn't upload that

if you need more I am happy to provide more

**Comment by takuya-takeuchi** [comment]
@SamuelvVelzen 

OK. I understand.
FaceRecognition.LoadImage` can accept raw image array. It means that you must decode jpg to raw bitmap.

````cs
            using (var ms = new MemoryStream(byteArr))
            {
                //Image image = Image.FromStream(ms);
                //width = image.Width;
                //height = image.Height;

                Bitmap bmp = new Bitmap(ms);
                width = bmp.Width;
                height = bmp.Height;
            }


            FaceImage img = FaceRecognition.LoadImage(byteArr, height, width, 3);
````

to

````cs
            byte[] raw = null;
            using (var ms = new MemoryStream(byteArr))
            {
                //Image image = Image.FromStream(ms);
                //width = image.Width;
                //height = image.Height;

                Bitmap bmp = new Bitmap(ms);
                width = bmp.Width;
                height = bmp.Height;

                var data = bmp.LockBits(new System.Drawing.Rectangle(0, 0, width, height),
                                        System.Drawing.Imaging.ImageLockMode.ReadOnly,
                                        bmp.PixelFormat);

                raw = new byte[width * height * 3];
                // pay attension stride if width is not multiple of 4
                // it is not available if width is not multiple of 4
                // And you may need to convert bmp from BGR to RGB
                System.Runtime.InteropServices.Marshal.Copy(data.Scan0, raw, 0, raw.Length);

                bmp.UnlockBits(data);
            }


            FaceImage img = FaceRecognition.LoadImage(raw, height, width, 3);
````

**Comment by SamuelvVelzen** [comment]
you specifically single out jpg does this mean that it doesn't work with a png?

**Comment by takuya-takeuchi** [comment]
@SamuelvVelzen 
Yes, jpg and png are encoded data. These are rgb pixel data but are complessed.
In Image processing domain, almost data should be raw data other than encoded data.

**Comment by SamuelvVelzen** [comment]
which image formats don't work? like .gif?

**Comment by takuya-takeuchi** [comment]
@SamuelvVelzen 
gif does not work.
Raw data is raw bitmap data.
http://fileformats.archiveteam.org/wiki/Raw_bitmap

The file size of raw bitmap data must be width x height x channel (1 or 3).
In other words, the file size of other file format could be less than it.

**Comment by takuya-takeuchi** [comment]
@SamuelvVelzen 
Next version, FRDN provide LoadImage(Bitmap)
1e1893a25d08719a149cb69445962d3b81358315

Thanks a lot.

**Comment by WellitonToledo** [comment]
Hi there! Any chance to provide an overload with SkiaSharp Bitmap to use it on Net7/Linux? 
Something like LoadImage(SKBitmap)

**Comment by takuya-takeuchi** [comment]
@WellitonToledo 
Move to #229
