### ISSUE TITLE
getting not found "shape_predictor_68_face_landmarks.dat"

### ISSUE THREAD

**Issue by balajikarthiq** [takuya-takeuchi/FaceRecognitionDotNet#95]
I've installed the nuget package as mentioned the wiki
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/wiki

I'm getting the error while create instance. I just created the folder c:\models and don't added anything in the models folder.

May I know how to solve the issue or what are the files need to add in the models directory

**Comment by takuya-takeuchi** [comment]
Please check the following instructions.
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/wiki/Quickstart#deploy-model-files

**Comment by balajikarthiq** [comment]
thanks
