### ISSUE TITLE
Age and gener models

### ISSUE THREAD

**Issue by alvaroiba** [takuya-takeuchi/FaceRecognitionDotNet#96]
Could you upload to github the pretrained models of "utkface-gender-network.dat" and "adience-age-network.dat"?

Thanks in advance.

**Comment by takuya-takeuchi** [comment]
@alvaroiba 
Very sorry. We should take care of license issue.
I don't know exact license of utkface and others.
So I can not upload pretrained data.

You can train them at your risk.

Thanks.

**Comment by atabora1** [comment]
Hi @takuya-takeuchi : I finished running the training script for the Gender program.
I get the following error when I attempt to use it. Is this feature still a work in progress?

![gender-error](https://user-images.githubusercontent.com/33614374/80439381-43719300-88bb-11ea-9e34-01948fa60e7b.PNG)

**Comment by takuya-takeuchi** [comment]
@atabora1 
Thank you for your challenging.
Please check how to use age/gender estimation.
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/wiki/Quickstart#6-agegender-estimation

**Comment by atabora1** [comment]
Thank you, that worked ;)

**Comment by takuya-takeuchi** [comment]
@alvaroiba 
Doesn't it usefull for you?
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/blob/master/examples/CustomClassificationDemo/Program.cs

**Comment by atabora1** [comment]
Thanks. Yes, this example is helpful. My mistake I was using an older example I had previously downloaded that didn't have the "using FaceRecognitionDotNet.Extensions;" statement. The Wiki link you sent me also didn't mention it so I was trying to figure out where this new function "SimpleGenderEstimator" came from. 

No problem. Intellisense helped me figure it out.

Old code I was using. Once again, thanks for the quick response. 


using System.Drawing;
using System.Linq;
using FaceRecognitionDotNet;

namespace CustomClassificationDemo
{

    internal class Program
    {

        #region Methods

        private static void Main()
        {
            var imageFile = "DianaPrincessOfWales_1997_36.jpg";

            using (var fr = FaceRecognition.Create("models"))
            using (var image = FaceRecognition.LoadImageFile(imageFile))
            using (var bitmap = (Bitmap)System.Drawing.Image.FromFile(imageFile))
            using (var g = Graphics.FromImage(bitmap))
            {
                var box = fr.FaceLocations(image, model: Model.Cnn).FirstOrDefault();

                using (var p = new Pen(Color.Red, bitmap.Width / 200f)) 
                    g.DrawRectangle(p, box.Left, box.Top, box.Right - box.Left, box.Bottom - box.Top);

                var ageRange = new[]
                {
                    "(0, 2)", 
                    "(4, 6)", 
                    "(8, 13)", 
                    "(15, 20)",
                    "(25, 32)",
                    "(38, 43)", 
                    "(48, 53)",
                    "(60, 100)"
                };
                //var age = ageRange[fr.PredictAge(image, box)];
				var age ="(15, 20)";
                var gender = fr.PredictGender(image, box);

                var agePos = new PointF(box.Left + 10, box.Top + 10);
                var genderPos = new PointF(box.Left + 10, box.Bottom - 50);
                g.DrawString(gender.ToString(), SystemFonts.CaptionFont, Brushes.Blue, agePos );
                g.DrawString(age, SystemFonts.CaptionFont, Brushes.Green, genderPos);

                bitmap.Save("result.png");
            }
        }

        #endregion

    }

}
